import { useId } from 'react'
import { CheckCircle2, CircleDashed, Clock3, ListPlus } from 'lucide-react'
import type { ManagementStats } from '@/types/management'
export function StatsCards({ stats, loading = false }: { stats: ManagementStats | null; loading?: boolean }) {
  const cards = [{ name: '今日新增', count: stats?.newToday, icon: ListPlus, color: '', note: '新记录，新的推进起点' }, { name: '今日完成', count: stats?.completedToday, icon: CheckCircle2, color: 'teal', note: '完成时间自动记录' }, { name: '待处理', count: stats?.todo, icon: CircleDashed, color: 'amber', note: `另有 ${stats?.doing ?? '—'} 条处理中` }, { name: '总体进度', count: stats ? `${stats.completionPercent}%` : undefined, icon: Clock3, color: 'blue', note: stats ? `${stats.done} / ${stats.activeTotal ?? stats.total} 个有效事件已完成` : '等待统计数据' }]
  return <div className="ws-stat-grid">{cards.map(card => <div className="ws-stat-card" key={card.name}><div className="ws-stat-top"><span>{card.name}</span><span className={`ws-stat-icon ${card.color}`}><card.icon size={15} /></span></div><strong className="ws-stat-value">{loading ? '…' : card.count ?? '—'}</strong><span className="ws-stat-caption">{card.note}</span></div>)}</div>
}
export function TrendChart({ stats }: { stats: ManagementStats }) {
  const id = useId(), trend = stats.trend
  const maximum = Math.max(1, Math.ceil(Math.max(0, ...trend.flatMap(point => [point.created, point.completed])) / 3)) * 3
  const x = (index: number) => 38 + index * 650 / Math.max(1, trend.length - 1), y = (value: number) => 145 - value * 115 / maximum
  const path = (field: 'created' | 'completed') => trend.map((point, index) => `${index ? 'L' : 'M'}${x(index)},${y(point[field])}`).join(' ')
  return <div className="ws-panel"><div className="ws-panel-head"><h3>项目推进趋势</h3><div className="ws-chart-legend"><span><i style={{ background: '#8f7be7' }} />新增</span><span><i style={{ background: '#42b498' }} />完成</span></div></div><div className="ws-panel-body"><svg className="ws-chart" viewBox="0 0 720 185" role="img" aria-labelledby={id}><title id={id}>当前筛选范围内最近 {trend.length} 天新增与完成事件趋势</title>{[0, 1, 2, 3].map(index => <g key={index}><line className="ws-chart-grid" x1="38" x2="698" y1={y(maximum * index / 3)} y2={y(maximum * index / 3)} /><text x="25" y={y(maximum * index / 3) + 3} textAnchor="end">{Math.round(maximum * index / 3)}</text></g>)}{trend.length > 0 && <><path d={`${path('created')} L${x(trend.length - 1)},145 L38,145 Z`} fill="#8f7be712" /><path d={path('created')} stroke="#8f7be7" strokeWidth="2.5" fill="none" strokeLinejoin="round" /><path d={path('completed')} stroke="#42b498" strokeWidth="2.5" fill="none" strokeLinejoin="round" />{trend.map((point, index) => <g key={point.date}><circle cx={x(index)} cy={y(point.created)} r="2.5" fill="#8f7be7"><title>{point.date} 新增 {point.created}</title></circle><circle cx={x(index)} cy={y(point.completed)} r="2.5" fill="#42b498"><title>{point.date} 完成 {point.completed}</title></circle>{(index % 3 === 0 || index === trend.length - 1) && <text x={x(index)} y="173" textAnchor="middle">{point.date.slice(5)}</text>}</g>)}</>}</svg><p className="ws-chart-note">真实事件记录 · 当前筛选范围 · {stats.today}</p></div></div>
}
export function Distribution({ stats }: { stats: ManagementStats }) {
  const items = stats.byCategory.filter(item => item.count > 0), total = items.reduce((sum, item) => sum + item.count, 0)
  let offset = 0
  const segments = items.map(item => { const start = offset; offset += item.count / Math.max(1, total) * 100; return `${item.color} ${start}% ${offset}%` })
  return <div className="ws-panel"><div className="ws-panel-head"><h3>事件分类分布</h3><small>{items.length} 个分类</small></div><div className="ws-distribution"><div className="ws-donut" role="img" aria-label={items.length ? items.map(item => `${item.name} ${item.count} 个`).join('，') : '暂无分类记录'} style={{ background: total ? `conic-gradient(${segments.join(',')})` : 'var(--ws-soft)' }}><div className="ws-donut-label"><strong>{total}</strong><small>当前范围事件</small></div></div><div className="ws-distribution-list">{items.length ? items.map(item => <div key={item.id}><span><i style={{ background: item.color }} />{item.name}</span><strong>{item.count}</strong></div>) : <p className="ws-setting-note">记录事件后，分类分布会自动更新。</p>}</div></div></div>
}
