import { useEffect, useState } from 'react'
import { Archive, ArrowUpRight, FolderOpen, Plus, Search } from 'lucide-react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { createProject, listProjects } from '@/services/management'
import type { ManagementProjectSummary } from '@/types/management'
import { EmptyState, ErrorNotice, PageIntro, timeLabel } from '@/components/workspace/ui'
import ProjectForm from './ProjectForm'
export default function ManagementPage() {
  const [projects, setProjects] = useState<ManagementProjectSummary[]>([])
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [search, setSearch] = useState(''), [archive, setArchive] = useState(false), [createOpen, setCreateOpen] = useState(false)
  const [params, setParams] = useSearchParams(), navigate = useNavigate()
  async function load() { setLoading(true); try { setProjects(await listProjects()); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : '项目列表读取失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (params.get('create') === '1') { setCreateOpen(true); setParams({}, { replace: true }) } }, [params])
  const active = projects.filter(project => !project.archivedAt), archived = projects.filter(project => Boolean(project.archivedAt))
  const shown = (archive ? archived : active).filter(project => `${project.name} ${project.description}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.updatedAt - a.updatedAt)
  return <><PageIntro eyebrow="PROJECT SPACE" title="把下一步，放进项目里" description="汇集需求、问题和设计，清楚地知道谁在推进、还需要做什么。"><button className="ws-button ws-button-primary" onClick={() => setCreateOpen(true)}><Plus size={15} />新建项目</button></PageIntro><ErrorNotice error={error} onRetry={() => void load()} /><div className="ws-toolbar"><div className="ws-toolbar-left"><div className="ws-tabs"><button className={!archive ? 'active' : ''} onClick={() => setArchive(false)}><FolderOpen size={14} />进行中 <span>{active.length}</span></button><button className={archive ? 'active' : ''} onClick={() => setArchive(true)}><Archive size={14} />已归档 <span>{archived.length}</span></button></div></div><div className="ws-search"><Search size={14} /><input aria-label="搜索项目" placeholder="搜索项目名称或说明…" value={search} onChange={event => setSearch(event.target.value)} /></div></div>{loading ? <div className="ws-skeleton-grid">{[0, 1, 2].map(index => <div className="ws-skeleton" key={index} />)}</div> : !shown.length ? <div className="ws-panel"><EmptyState title={search ? '没有找到这个项目' : archive ? '归档的项目会在这里安静保存' : '从一个目标，开始整理'} description={search ? '换一个关键词，或清空搜索查看所有项目。' : archive ? '归档保留事件、设计与操作记录，需要时可以继续推进。' : '新建项目，自定义角色和事件分类，再把画布与需求连接起来。'}>{!search && !archive && <button className="ws-button ws-button-primary" onClick={() => setCreateOpen(true)}><Plus size={14} />创建第一个项目</button>}</EmptyState></div> : <div className="ws-grid">{shown.map(project => <Link className="ws-panel ws-project-card" key={project.id} to={`/projects/${project.id}`}><div className="ws-project-card-top"><span className="ws-project-mark" style={{ background: `${project.color}18`, color: project.color }}>{project.name.slice(0, 1)}</span>{project.archivedAt ? <span className="ws-tag">已归档</span> : <ArrowUpRight size={16} style={{ color: 'var(--ws-muted)' }} />}</div><h3>{project.name}</h3><p>{project.description || '添加项目说明，让目标更清晰。'}</p><div className="ws-project-meta"><span>{project.eventCount} 个事件 · {project.canvasIds.length} 张画布</span><span>{project.stats.completionPercent}%</span></div><div className="ws-progress"><span style={{ width: `${project.stats.completionPercent}%`, background: project.color }} /></div><div className="ws-project-card-bottom"><div className="ws-role-dots">{project.roles.slice(0, 4).map(role => <span key={role.id} title={role.name} style={{ background: `${role.color}22`, color: role.color }}>{role.name.slice(0, 1)}</span>)}</div><span>{timeLabel(project.updatedAt)}</span></div></Link>)}</div>}{createOpen && <ProjectForm onClose={() => setCreateOpen(false)} onSave={async (draft, actionId) => { const project = await createProject(draft, { mutationId: actionId }); navigate(`/projects/${project.id}`, { state: { setupTable: true } }) }} />}</>
}
