import { useEffect, useRef, useState } from 'react'
import { Check, Pencil, X } from 'lucide-react'
import { ManagementRequestError } from '@/services/management'
import type { CustomFieldType } from './TableSetupWizard'
export type CellValue = string | number | boolean | undefined
export default function InlineValue({ value, type = 'text', options = [], label, disabled = false, onSave, children, version, allowEmpty = true }: { value: CellValue; type?: CustomFieldType; options?: Array<string | { value: string; label: string }>; label: string; disabled?: boolean; onSave: (value: CellValue, base: CellValue, version?: number) => Promise<void>; version?: number; children?: React.ReactNode; allowEmpty?: boolean }) {
  const [editing, setEditing] = useState(false), [draft, setDraft] = useState(String(value ?? '')), [busy, setBusy] = useState(false), [error, setError] = useState(''), [conflict, setConflict] = useState(false)
  const working = useRef(false), latest = useRef(draft), original = useRef(value), editVersion = useRef(version), pendingValue = useRef<CellValue>(undefined)
  latest.current = draft
  useEffect(() => { if (!editing) { setDraft(String(value ?? '')); original.current = value } }, [value, editing])
  async function commit(next?: CellValue) {
    if (working.current) return
    const typed = next !== undefined ? next : type === 'checkbox' ? pendingValue.current ?? value : type === 'number' ? latest.current === '' ? undefined : Number(latest.current) : latest.current
    if (type === 'number' && typed !== undefined && !Number.isFinite(typed)) { setError('请输入有效数字'); return }
    if (typed === value || (typed === '' && value === undefined)) { setEditing(false); setError(''); setConflict(false); return }
    pendingValue.current = typed
    working.current = true; setBusy(true); setError(''); setConflict(false)
    try { await onSave(typed, original.current, editVersion.current); setEditing(false) } catch (cause) { if (cause instanceof Error && cause.name === 'TransitionCancelled') { setEditing(false); setError('') } else setError(cause instanceof Error ? cause.message : '保存失败，内容仍保留'); setConflict(cause instanceof ManagementRequestError && cause.status === 409) } finally { working.current = false; setBusy(false) }
  }
  if (type === 'checkbox') return <div className="ws-inline-cell"><input className="ws-check" type="checkbox" aria-label={label} checked={value === true} disabled={disabled || busy} onChange={event => { original.current = value; editVersion.current = version; void commit(event.target.checked) }} />{error && <small role="alert">{error}</small>}{conflict && <div className="ws-inline-conflict"><span>最新值：{String(value ?? '未填写')}</span><button type="button" onMouseDown={event => event.preventDefault()} onClick={() => { setDraft(String(value ?? '')); original.current = value; editVersion.current = version; setEditing(false); setError(''); setConflict(false) }}>采用最新值</button><button type="button" onMouseDown={event => event.preventDefault()} onClick={() => { original.current = value; editVersion.current = version; void commit() }}>保留我的修改</button></div>}</div>
  const input = editing ? <div className="ws-inline-editor">{type === 'select' ? <select autoFocus aria-label={label} value={draft} disabled={busy} onChange={event => setDraft(event.target.value)} onBlur={() => void commit()}>{allowEmpty && !options.some(option => (typeof option === 'string' ? option : option.value) === '') && <option value="">未填写</option>}{options.map(option => <option key={typeof option === 'string' ? option : option.value} value={typeof option === 'string' ? option : option.value}>{typeof option === 'string' ? option : option.label}</option>)}</select> : <input autoFocus aria-label={label} type={type === 'number' ? 'number' : type === 'date' ? 'date' : 'text'} step={type === 'number' ? 'any' : undefined} value={draft} disabled={busy} onChange={event => setDraft(event.target.value)} onBlur={() => void commit()} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); void commit() }; if (event.key === 'Escape') { event.preventDefault(); latest.current = String(original.current ?? ''); setDraft(latest.current); setEditing(false); setError('') } }} />}<button type="button" className="ws-icon-button" aria-label={`保存 ${label}`} disabled={busy} onMouseDown={event => event.preventDefault()} onClick={() => void commit()}><Check size={11} /></button>{!busy && <button type="button" className="ws-icon-button" aria-label={`取消编辑 ${label}`} onMouseDown={event => event.preventDefault()} onClick={() => { latest.current = String(original.current ?? ''); setDraft(latest.current); setEditing(false); setError('') }}><X size={11} /></button>}</div> : <button type="button" className="ws-inline-open" aria-label={`编辑 ${label}`} disabled={disabled} onClick={() => { original.current = value; editVersion.current = version; setDraft(String(value ?? '')); setEditing(true); setError('') }}>{children ?? (value === undefined || value === '' ? <span className="ws-inline-placeholder">点击填写</span> : String(value))}<Pencil size={10} /></button>
  return <div className="ws-inline-cell">{input}{error && <small role="alert">{error}</small>}{conflict && <div className="ws-inline-conflict"><span>最新值：{String(value ?? '未填写')}</span><button type="button" onMouseDown={event => event.preventDefault()} onClick={() => { setDraft(String(value ?? '')); original.current = value; editVersion.current = version; setEditing(false); setError(''); setConflict(false) }}>采用最新值</button><button type="button" onMouseDown={event => event.preventDefault()} onClick={() => { original.current = value; editVersion.current = version; void commit() }}>保留我的修改</button></div>}</div>
}
