import { useCallback, useEffect, useRef, useState } from 'react'
import { Archive, ArrowLeft, ArrowUpRight, Check, Clock3, Columns3, LayoutDashboard, Layers, List, Paperclip, Pencil, Plus, Search, Settings2, Sparkles, Trash2, UserPlus, X } from 'lucide-react'
import { Link, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import AIShareDialog from '@/components/workspace/AIShareDialog'
import { ErrorNotice, ModalCancelButton, WorkspaceModal, timeLabel } from '@/components/workspace/ui'
import { useWorkspace } from '@/components/workspace/WorkspaceShell'
import { createEvent, createTag, deleteEvent, deleteTag, getEvents, getStats, getMembers, notifyEvent, setupTable, ManagementRequestError, updateEvent, updateProject, updateTag } from '@/services/management'
import type { EventDraft, ManagementEvent, ManagementFilters, ManagementProject, ManagementStats, ManagementStatus, ManagementTag, ManagementMember, EventUpdatePatch, MutationOptions } from '@/types/management'
import { generateId, getAllDocuments, saveDocument } from '@/utils/storage'
import type { StoredDocument } from '@/utils/storage'
import EventModal from './EventModal'
import ProjectForm from './ProjectForm'
import { Distribution, StatsCards, TrendChart } from './Charts'
import { historyChanges, historyTitle, priorities, priorityName, statuses } from './model'
import { TransitionCancelled, TransitionDialog } from './WorkflowStatus'
import { useShanghaiToday } from '@/components/workspace/useToday'
import { connectProjectLive } from '@/services/managementLive'
import type { OnlineMember } from '@/services/managementLive'
import InlineIssuesTable from './InlineIssuesTable'
import type { CellGuard } from './InlineIssuesTable'
import type { CellValue } from './InlineValue'
import TableSetupWizard, { baseColumnChoices } from './TableSetupWizard'
import type { SetupDraft } from './TableSetupWizard'
import MemberSettings from './MemberSettings'
import ProjectInviteDialog from './ProjectInviteDialog'
import { useProject } from './useProject'

type View = 'table' | 'board' | 'overview' | 'settings'
type Invoke = (request: (value: ManagementProject) => Promise<ManagementProject>) => Promise<ManagementProject>
function Tag({ tag }: { tag?: ManagementTag }) { return tag ? <span className="ws-tag" style={{ background: `${tag.color}18`, color: tag.color }}><i />{tag.name}</span> : <span className="ws-tag">未分类</span> }
function TagRow({ tag, onSave, onDelete, busy }: { tag: ManagementTag; onSave: (value: ManagementTag) => Promise<void>; onDelete: () => Promise<void>; busy: boolean }) {
  const [value, setValue] = useState(tag), [error, setError] = useState('')
  useEffect(() => setValue(tag), [tag.id, tag.name, tag.color])
  const dirty = value.name !== tag.name || value.color !== tag.color
  async function save() { if (!value.name.trim()) { setError('请填写分类名称'); return }; try { await onSave({ ...value, name: value.name.trim() }); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : '保存失败') } }
  return <div><div className="ws-tag-editor"><input type="color" aria-label={`${tag.name} 的颜色`} value={value.color} onChange={event => setValue(previous => ({ ...previous, color: event.target.value }))} /><input type="text" aria-label={`分类名称 ${tag.name}`} value={value.name} maxLength={80} onChange={event => setValue(previous => ({ ...previous, name: event.target.value }))} /><button className="ws-icon-button" aria-label={`保存分类 ${tag.name}`} disabled={busy || !dirty} onClick={() => void save()}><Check size={15} /></button><button className="ws-icon-button" aria-label={`删除分类 ${tag.name}`} disabled={busy} onClick={() => void onDelete().catch(cause => setError(cause instanceof Error ? cause.message : '删除失败'))}><Trash2 size={14} /></button></div>{error && <p className="ws-setting-note" role="alert" style={{ color: '#c76877' }}>{error}</p>}</div>
}
function TagSettings({ project, kind, invoke, busy }: { project: ManagementProject; kind: 'roles' | 'categories'; invoke: Invoke; busy: boolean }) {
  const [name, setName] = useState(''), [error, setError] = useState('')
  async function add() { if (!name.trim()) return; try { await invoke(current => createTag(current.id, kind, { name: name.trim(), color: kind === 'roles' ? '#7963e9' : '#35a58b' }, { revision: current.revision })); setName(''); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : '新增失败') } }
  return <section className="ws-panel"><div className="ws-panel-head"><h3>{kind === 'roles' ? '角色分类' : '事件分类'}</h3><small>{project[kind].length} 个</small></div><div className="ws-panel-body">{project[kind].map(tag => <TagRow key={tag.id} tag={tag} busy={busy} onSave={async value => { await invoke(current => updateTag(current.id, kind, tag.id, { name: value.name, color: value.color }, { revision: current.revision })) }} onDelete={async () => { await invoke(current => deleteTag(current.id, kind, tag.id, { revision: current.revision })) }} />)}{!project[kind].length && <p className="ws-setting-note">{kind === 'roles' ? '创建适合你团队的角色，如技术、策划或美工。' : '用自己的分类整理需求、问题和日常事项。'}</p>}<div className="ws-add-tag"><input aria-label={kind === 'roles' ? '新增角色名称' : '新增事件分类名称'} value={name} maxLength={80} placeholder={kind === 'roles' ? '输入新角色名称' : '输入新分类名称'} onChange={event => setName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void add() }} /><button className="ws-button ws-button-small" disabled={busy || !name.trim()} onClick={() => void add()}><Plus size={13} />添加</button></div><ErrorNotice error={error} /><p className="ws-setting-note">修改名称或颜色后，点击勾选保存。已有事件使用的分类可以编辑，需先调整事件分类才能删除。</p></div></section>
}
function CanvasPicker({ project, documents, onSave, onClose }: { project: ManagementProject; documents: StoredDocument[]; onSave: (ids: string[]) => Promise<void>; onClose: () => void }) {
  const [ids, setIds] = useState(project.canvasIds), [search, setSearch] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const original = useRef(JSON.stringify(project.canvasIds))
  const owned = documents.filter(document => (!document.permission || document.permission === 'owner') && document.title.toLowerCase().includes(search.toLowerCase()))
  return <WorkspaceModal title="连接你的设计画布" description="把已有画布与项目关联，让需求和设计可以一起读取。" onClose={onClose} dirty={JSON.stringify(ids) !== original.current} busy={busy}><div className="ws-form"><ErrorNotice error={error} /><div className="ws-search" style={{ maxWidth: 'none', marginBottom: 15 }}><Search size={14} /><input aria-label="搜索待关联画布" value={search} placeholder="搜索我的画布…" onChange={event => setSearch(event.target.value)} /></div><div className="ws-scroll-section">{owned.map(document => <label className="ws-choice-row" key={document.id}><input type="checkbox" className="ws-check" checked={ids.includes(document.id)} onChange={() => setIds(previous => previous.includes(document.id) ? previous.filter(id => id !== document.id) : [...previous, document.id])} />{document.thumbnail ? <img src={document.thumbnail} alt="" /> : <Layers size={18} />}<span>{document.title}<small>更新于 {timeLabel(document.updatedAt)}</small></span></label>)}{!owned.length && <p className="ws-setting-note">没有找到画布。可以先创建一张新的设计画布。</p>}</div><div className="ws-modal-actions"><span>已选择 {ids.length} 张</span><ModalCancelButton /><button className="ws-button ws-button-primary" disabled={busy} onClick={() => { setBusy(true); void onSave(ids).then(onClose).catch(cause => setError(cause instanceof Error ? cause.message : '关联失败')).finally(() => setBusy(false)) }}><Check size={14} />{busy ? '正在保存…' : '保存关联'}</button></div></div></WorkspaceModal>
}
export default function ProjectPage() {
  const { projectId = '' } = useParams<{ projectId: string }>()
  const { user } = useWorkspace(), navigate = useNavigate(), location = useLocation()
  const { project, loading, error, busy, reload, invoke, accept, permissionDenied } = useProject(projectId)
  const [params, setParams] = useSearchParams()
  const [members, setMembers] = useState<ManagementMember[]>([]), [membersError, setMembersError] = useState(''), [setupOpen, setSetupOpen] = useState(false), [newRowSignal, setNewRowSignal] = useState(0)
  const [online, setOnline] = useState<OnlineMember[]>([]), [connected, setConnected] = useState(false)
  const currentProject = useRef(project), reloadRef = useRef(reload); currentProject.current = project; reloadRef.current = reload
  const isOwner = Boolean(project && (project.ownerId === user.id || project.access === 'owner')), canEdit = Boolean(project && (isOwner || project.access === 'edit'))
  const requested = params.get('view')
  const view: View = requested === 'board' || requested === 'overview' || requested === 'settings' ? requested : 'table'
  const [filters, setFilters] = useState<ManagementFilters>({ roleId: params.get('roleId') || undefined }), [events, setEvents] = useState<ManagementEvent[]>([]), [stats, setStats] = useState<ManagementStats | null>(null), [filterLoading, setFilterLoading] = useState(true), [filterError, setFilterError] = useState('')
  const [documents, setDocuments] = useState<StoredDocument[]>([]), [documentError, setDocumentError] = useState('')
  const [editEvent, setEditEvent] = useState<ManagementEvent | null>(null), [createOpen, setCreateOpen] = useState(false), [editProject, setEditProject] = useState(false), [aiOpen, setAIOpen] = useState(false), [inviteOpen, setInviteOpen] = useState(false), [pickerOpen, setPickerOpen] = useState(false), [deleteTarget, setDeleteTarget] = useState<ManagementEvent | null>(null), [dragStatus, setDragStatus] = useState<ManagementStatus | null>(null)
  const dayKey = useShanghaiToday()
  const [transition, setTransition] = useState<{ event: ManagementEvent; patch: EventUpdatePatch; guard?: MutationOptions; resolve: () => void; reject: (error: Error) => void; projectId: string } | null>(null)
  const transitionRef = useRef(transition); transitionRef.current = transition
  useEffect(() => { const focus = () => { void reloadRef.current() }; window.addEventListener('focus', focus); return () => window.removeEventListener('focus', focus) }, [projectId])
  const filtersKey = JSON.stringify(filters)
  useEffect(() => { let canceled = false; void getMembers().then(values => { if (!canceled) { setMembers(values); setMembersError('') } }).catch(cause => { if (!canceled) setMembersError(cause instanceof Error ? cause.message : '成员目录读取失败') }); return () => { canceled = true } }, [projectId])
  useEffect(() => {
    if (!projectId || permissionDenied) return
    let disposed = false, refreshing = false, again = false
    async function refresh() { if (refreshing) { again = true; return }; refreshing = true; do { again = false; if (!disposed) await reloadRef.current() } while (again && !disposed); refreshing = false }
    const stop = connectProjectLive(projectId, { snapshot: value => { if (!disposed) accept(value) }, revision: (revision, force) => { if (force || revision > (currentProject.current?.revision ?? -1)) void refresh() }, presence: values => { if (!disposed) setOnline(values) }, state: value => { if (!disposed) { setConnected(value); if (!value) void refresh() } } })
    return () => { disposed = true; stop(); setOnline([]); setConnected(false) }
  }, [projectId, accept, permissionDenied])
  useEffect(() => { if (project && isOwner && !project.roles.length && (location.state as { setupTable?: boolean } | null)?.setupTable) { setSetupOpen(true); navigate(location.pathname + location.search, { replace: true, state: null }) } }, [project?.id, isOwner, location.state])
  useEffect(() => { setFilters({ roleId: params.get('roleId') || undefined }); setStats(null); setEvents([]); setEditEvent(null); setCreateOpen(false); setSetupOpen(false); setAIOpen(false); setInviteOpen(false); setPickerOpen(false); setEditProject(false); setDeleteTarget(null); setNewRowSignal(0); transitionRef.current?.reject(new TransitionCancelled()); transitionRef.current = null; setTransition(null) }, [projectId])
  useEffect(() => { let canceled = false; if (!project) return; setFilterLoading(true); const timer = window.setTimeout(() => { void Promise.all([getEvents(project.id, filters), getStats(project.id, filters)]).then(([rows, values]) => { if (!canceled) { setEvents(rows); setStats(values); setFilterError('') } }).catch(cause => { if (!canceled) { setFilterError(cause instanceof Error ? cause.message : '事件与统计读取失败'); setStats(null); setEvents([]) } }).finally(() => { if (!canceled) setFilterLoading(false) }) }, 220); return () => { canceled = true; window.clearTimeout(timer) } }, [project?.id, project?.revision, filtersKey, dayKey])
  const loadDocuments = useCallback(async () => { try { setDocuments(await getAllDocuments()); setDocumentError('') } catch (cause) { setDocumentError(cause instanceof Error ? cause.message : '关联画布读取失败') } }, [])
  useEffect(() => { void loadDocuments() }, [loadDocuments])
  const setView = (next: View) => setParams({ view: next })
  async function status(event: ManagementEvent, value: ManagementStatus) { if (!canEdit || event.status === value) return; try { await patchEvent(event.id, { status: value }, { updatedAt: event.updatedAt, baseValues: { status: event.status } }) } catch { /* visible state is retained */ } }
  function askTransition(event: ManagementEvent, patch: EventUpdatePatch, guard?: MutationOptions): Promise<void> { return new Promise((resolve, reject) => { if (transitionRef.current) { reject(new Error('请先完成当前阶段说明。')); return }; const value = { event, patch, guard, resolve, reject, projectId }; transitionRef.current = value; setTransition(value) }) }
  function cancelTransition() { const value = transitionRef.current; if (value) { transitionRef.current = null; setTransition(null); value.reject(new TransitionCancelled()) } }
  async function confirmTransition(note: string) { const value = transitionRef.current; if (!value || value.projectId !== projectId || !canEdit) throw new Error('当前已无法编辑这条问题。'); await invoke(current => updateEvent(current.id, value.event.id, { ...value.patch, ...(note ? { transitionNote: note } : {}) }, { revision: current.revision, ...value.guard })); transitionRef.current = null; setTransition(null); value.resolve() }

  async function createCanvas() { if (!project) return; try { const id = generateId(), now = Date.now(); await saveDocument({ id, title: `${project.name} · 设计画布`, content: '', createdAt: now, updatedAt: now }); await invoke(current => updateProject(current.id, { canvasIds: [...current.canvasIds, id] }, { revision: current.revision })); navigate(`/editor/${id}`) } catch (cause) { setDocumentError(cause instanceof Error ? cause.message : '画布创建或关联失败；可在画布列表中重新关联。') } }
  async function saveEvent(draft: EventDraft, actionId: string, changes?: EventUpdatePatch, guard?: MutationOptions) { if (editEvent && changes?.status && ['rejected', 'blocked', 'on_hold', 'cancelled'].includes(changes.status)) { const current = currentProject.current?.events.find(event => event.id === editEvent.id); if (current && current.status !== changes.status) { await askTransition(current, changes, { ...guard, mutationId: actionId }); return } }; await invoke(current => editEvent ? updateEvent(current.id, editEvent.id, changes ?? draft, { revision: current.revision, mutationId: actionId, ...guard }) : createEvent(current.id, { ...draft, id: `event_${actionId}` }, { revision: current.revision, mutationId: actionId })) }

  async function patchEvent(id: string, patch: Partial<EventDraft>, guard?: CellGuard) {
    const event = currentProject.current?.events.find(value => value.id === id); if (event && patch.status && patch.status !== event.status && ['rejected', 'blocked', 'on_hold', 'cancelled'].includes(patch.status)) { await askTransition(event, patch, guard ? { expectedEventUpdatedAt: guard.updatedAt, baseValues: guard.baseValues } : undefined); return }
    try { await invoke(current => updateEvent(current.id, id, patch, { revision: current.revision, ...(guard ? { expectedEventUpdatedAt: guard.updatedAt, baseValues: guard.baseValues } : {}) })) } catch (cause) { if (cause instanceof ManagementRequestError && cause.status === 409) await reload(); throw cause }
  }
  async function patchValue(id: string, fieldId: string, value: CellValue, base: CellValue, version?: number) {
    try { await invoke(current => updateEvent(current.id, id, { values: { [fieldId]: value ?? null } }, { revision: current.revision, expectedEventUpdatedAt: version, baseValues: { values: { [fieldId]: base ?? null } } })) } catch (cause) { if (cause instanceof ManagementRequestError && cause.status === 409) await reload(); throw cause }
  }
  async function newRow(draft: EventDraft, actionId: string, eventId: string) { const result = await invoke(current => createEvent(current.id, { ...draft, id: eventId }, { revision: current.revision, mutationId: actionId })); const created = result.events.find(event => event.id === eventId); if (!created) throw new Error('创建状态需要重新确认；当前输入仍保留。'); return created }
  async function push(event: ManagementEvent, actionId: string) { if (!canEdit) throw new Error('当前项目为只读'); const result = await notifyEvent(projectId, event.id, event.recipientIds ?? [], actionId); await reload(); window.dispatchEvent(new Event('workspace:notifications-changed')); return result }
  async function generateTable(draft: SetupDraft) { await invoke(current => setupTable(current.id, draft.roles, { configured: true, visibleBaseFields: draft.columns.filter(column => column.visible).map(column => column.key), baseLabels: Object.fromEntries(draft.columns.map(column => [column.key, column.label])), customFields: draft.fields }, { revision: current.revision })); setView('table') }
  const tagFor = (kind: 'roles' | 'categories', id: string) => project?.[kind].find(tag => tag.id === id)
  if (loading && !project) return <div className="ws-loading">正在打开项目空间…</div>
  if (!project) return <><ErrorNotice error={error} onRetry={() => void reload()} /><Link className="ws-button" to="/projects"><ArrowLeft size={14} />返回项目列表</Link></>
  const history = [...project.history].sort((a, b) => b.at - a.at)
  const linked = project.canvasIds.map(id => documents.find(document => document.id === id)).filter((document): document is StoredDocument => Boolean(document))
  return <><div className="ws-page-intro"><div className="ws-project-heading"><span className="ws-project-mark" style={{ background: `${project.color}18`, color: project.color }}>{project.name.slice(0, 1)}</span><div><p className="ws-eyebrow">PROJECT WORKSPACE</p><h1>{project.name}</h1><p className="ws-page-description">{project.description || '连接需求、设计与每一步推进。'}</p></div></div><div className="ws-intro-actions">{isOwner && <button className="ws-button" onClick={() => setInviteOpen(true)}><UserPlus size={14} />邀请成员</button>}{isOwner && <button className="ws-button" onClick={() => setAIOpen(true)}><Sparkles size={14} />交给 AI</button>}{canEdit && <button className="ws-button ws-button-primary" onClick={() => { if (!project.roles.length) { if (isOwner) setSetupOpen(true); return }; if (view === 'table') setNewRowSignal(value => value + 1); else setCreateOpen(true) }} disabled={busy || (!project.roles.length && !isOwner)}><Plus size={15} />{!project.roles.length ? '先创建角色与表格' : view === 'table' ? '新增一行写问题' : '记录事件'}</button>}</div></div><ErrorNotice error={error} onRetry={() => void reload()} /><ErrorNotice error={filterError} onRetry={() => void reload()} /><ErrorNotice error={membersError} /><div className="ws-live-bar"><span className="ws-tag">{isOwner ? '创建者' : canEdit ? '可编辑问题' : '只读成员'}</span><div className="ws-online-avatars">{online.slice(0, 5).map(member => <span key={member.userId} title={`${member.name}${member.sessions > 1 ? ` · ${member.sessions} 个会话` : ''}`}>{member.name.slice(0, 1)}</span>)}</div><span className="ws-saved-note"><i style={{ background: connected ? 'var(--ws-teal)' : 'var(--ws-muted)' }} />{connected ? `${online.length} 人在线` : '协作连接中…'}</span></div>{!project.roles.length && <div className="ws-setup-banner"><div><h3>先建立角色，再生成你的问题表格</h3><p>设置角色和需要记录的字段，之后就可以直接在表格里写问题、选人推送。</p></div>{isOwner ? <button className="ws-button ws-button-primary" onClick={() => setSetupOpen(true)}><Plus size={14} />开始设置表格</button> : <span className="ws-setting-note">等待创建者完成表格设置</span>}</div>}{project.archivedAt && <div className="ws-archived-banner"><span>这个项目已归档，事件和设计仍完整保存。</span>{isOwner && <button className="ws-button ws-button-small" disabled={busy} onClick={() => void invoke(current => updateProject(current.id, { archived: false }, { revision: current.revision })).catch(() => {})}>继续推进</button>}</div>}
    <StatsCards stats={stats} loading={filterLoading} /><div className="ws-project-nav" role="tablist" aria-label="项目视图">{[{ id: 'table' as View, name: '事件表格', icon: List }, { id: 'board' as View, name: '进度看板', icon: Columns3 }, { id: 'overview' as View, name: '项目概览', icon: LayoutDashboard }, { id: 'settings' as View, name: '项目设置', icon: Settings2 }].filter(item => item.id !== 'settings' || isOwner).map(item => <button role="tab" aria-selected={view === item.id} className={view === item.id ? 'active' : ''} key={item.id} onClick={() => setView(item.id)}><item.icon size={14} />{item.name}</button>)}<span className="ws-saved-note" style={{ marginLeft: 'auto', alignSelf: 'start' }}><i />{busy ? '正在保存…' : error ? '保存未确认' : '已同步'}</span></div>
    {view !== 'settings' && <><div className="ws-role-tabs"><button className={`ws-role-tab ${!filters.roleId ? 'active' : ''}`} onClick={() => setFilters(previous => ({ ...previous, roleId: undefined }))}>全部角色 <span>{project.events.length}</span></button>{project.roles.map(role => <button className={`ws-role-tab ${filters.roleId === role.id ? 'active' : ''}`} key={role.id} onClick={() => setFilters(previous => ({ ...previous, roleId: role.id }))}><i style={{ background: role.color }} />{role.name}<span>{project.events.filter(event => event.roleId === role.id).length}</span></button>)}{project.events.some(event => !event.roleId) && <button className={`ws-role-tab ${filters.roleId === '__unassigned__' ? 'active' : ''}`} onClick={() => setFilters(previous => ({ ...previous, roleId: '__unassigned__' }))}>未分配角色 <span>{project.events.filter(event => !event.roleId).length}</span></button>}{isOwner && <button className="ws-link-button" onClick={() => setSetupOpen(true)}><Settings2 size={12} />表格设置</button>}</div><div className="ws-toolbar"><div className="ws-toolbar-left"><div className="ws-search"><Search size={14} /><input aria-label="搜索项目事件" value={filters.search ?? ''} placeholder="搜索标题、描述或处理人…" onChange={event => setFilters(previous => ({ ...previous, search: event.target.value }))} /></div></div><div className="ws-toolbar-right"><select className="ws-filter-select" aria-label="筛选事件分类" value={filters.categoryId ?? ''} onChange={event => setFilters(previous => ({ ...previous, categoryId: event.target.value || undefined }))}><option value="">全部事件分类</option>{project.categories.map(tag => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><select className="ws-filter-select" aria-label="筛选处理状态" value={filters.status ?? ''} onChange={event => setFilters(previous => ({ ...previous, status: event.target.value as ManagementFilters['status'] || undefined }))}><option value="">全部状态</option>{statuses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="ws-filter-select" aria-label="筛选优先级" value={filters.priority ?? ''} onChange={event => setFilters(previous => ({ ...previous, priority: event.target.value as ManagementFilters['priority'] || undefined }))}><option value="">全部优先级</option>{priorities.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{Object.values(filters).some(Boolean) && <button className="ws-icon-button" aria-label="清空筛选条件" onClick={() => setFilters({})}><X size={15} /></button>}</div></div></>}
    {view === 'table' && <InlineIssuesTable key={`table:${project.id}`} project={project} events={events.map(event => project.events.find(value => value.id === event.id) ?? event)} members={members} roleId={filters.roleId} loading={filterLoading} busy={busy} createSignal={newRowSignal} filterError={filterError} onPatch={patchEvent} onValue={patchValue} onCreate={newRow} onNotify={push} onDetails={setEditEvent} onDelete={setDeleteTarget} onSetup={() => setSetupOpen(true)} recorder={user.email} canEdit={canEdit} canConfigure={isOwner} />}

    {view === 'board' && (filterLoading ? <div className="ws-loading">正在更新进度看板…</div> : <div className="ws-board">{statuses.map(column => { const rows = events.filter(event => event.status === column.id); return <section className={`ws-board-column ${dragStatus === column.id ? 'dragover' : ''}`} key={column.id} onDragOver={event => { event.preventDefault(); setDragStatus(column.id) }} onDragLeave={event => { if (!event.currentTarget.contains(event.relatedTarget as Node | null)) setDragStatus(null) }} onDrop={event => { event.preventDefault(); setDragStatus(null); const target = project.events.find(item => item.id === event.dataTransfer.getData('application/x-flowboard-event')); if (target) void status(target, column.id) }}><div className="ws-board-head"><span><i className={`ws-tag ws-status-${column.id}`}><i />{column.name}</i></span><small>{rows.length}</small></div>{rows.map(event => <article className="ws-board-card" key={event.id} draggable={!busy && canEdit} onDragStart={value => value.dataTransfer.setData('application/x-flowboard-event', event.id)} onDragEnd={() => setDragStatus(null)}><div style={{ display: 'flex', justifyContent: 'space-between' }}><Tag tag={tagFor('categories', event.categoryId)} /><span className={`ws-tag ws-priority-${event.priority}`}>{priorityName(event.priority)}</span></div><h3><button onClick={() => setEditEvent(event)}>{event.title}</button></h3><p>{event.description || '点击补充这件事的具体要求。'}</p><div className="ws-board-card-foot"><span className="ws-person"><i className="ws-person-circle">{event.assignee?.slice(0, 1) || '·'}</i>{event.assignee || '待分配'}{event.attachments.length > 0 && <Paperclip size={10} />}</span><select aria-label={`${event.title} 的处理状态`} disabled={busy || !canEdit} value={event.status} onChange={value => void status(event, value.target.value as ManagementStatus)}>{statuses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></article>)}{!rows.length && <p className="ws-setting-note">没有{column.name}的事件。</p>}</section> })}</div>)}
    {view === 'overview' && <>{filterLoading ? <div className="ws-loading">正在计算当前范围统计…</div> : stats && <div className="ws-two-column"><TrendChart stats={stats} /><Distribution stats={stats} /></div>}<div className="ws-two-column" style={{ marginTop: 20 }}><section className="ws-panel"><div className="ws-panel-head"><h3>最近的推进记录</h3><small>自动记录</small></div><div className="ws-panel-body">{history.slice(0, 7).map(item => <div className="ws-activity" key={item.id}><span className="ws-activity-icon"><Clock3 size={13} /></span><div><p>{historyTitle(item)}</p><div className="ws-history-change">{historyChanges(item)}</div><small>{timeLabel(item.at)} · {item.actorId === user.id ? user.email : '项目成员'}</small></div></div>)}{!history.length && <p className="ws-setting-note">项目的新增、编辑和完成操作会自动记录在这里。</p>}</div></section><section className="ws-panel"><div className="ws-panel-head"><h3>处理进度</h3><small>当前筛选</small></div><div className="ws-panel-body"><div className="ws-milestone"><div className="ws-progress-ring" style={{ background: `conic-gradient(var(--ws-teal) 0% ${stats?.completionPercent ?? 0}%,var(--ws-soft) ${stats?.completionPercent ?? 0}% 100%)` }}><span>{stats?.completionPercent ?? '—'}%</span></div><p><strong>每一步都有记录</strong>{stats?.done ?? '—'} 个事件已完成，继续推进剩余事项。</p></div>{statuses.map(item => <div className="ws-stat-row" key={item.id}><span>{item.name}</span><strong>{stats?.byStatus.find(value => value.id === item.id)?.count ?? '—'}</strong></div>)}</div></section></div></>}
    {view === 'settings' && isOwner && <><section className="ws-panel" style={{ marginBottom: 20 }}><div className="ws-panel-head"><h3>项目目标与信息</h3><button className="ws-button ws-button-small" onClick={() => setEditProject(true)}><Pencil size={13} />编辑</button></div><div className="ws-panel-body"><p className="ws-project-description">{project.description || '添加项目目标和说明，让协作更容易理解。'}</p><div className="ws-divider" /><div className="ws-toolbar" style={{ marginBottom: 0 }}><span className="ws-setting-note">创建于 {timeLabel(project.createdAt, true)}</span><button className="ws-button ws-button-small" disabled={busy} onClick={() => void invoke(current => updateProject(current.id, { archived: !current.archivedAt }, { revision: current.revision })).catch(() => {})}><Archive size={13} />{project.archivedAt ? '恢复项目' : '归档项目'}</button></div></div></section><div className="ws-toolbar"><button className="ws-button" onClick={() => setSetupOpen(true)}><Settings2 size={14} />编辑表格字段与角色</button></div><div className="ws-settings-grid"><TagSettings project={project} kind="roles" invoke={invoke} busy={busy} /><TagSettings project={project} kind="categories" invoke={invoke} busy={busy} /></div><MemberSettings key={`members:${project.id}`} project={project} members={members} busy={busy} onRefresh={reload} onInvite={() => setInviteOpen(true)} onSave={async (members, revision) => invoke(current => updateProject(current.id, { members }, { revision }))} /></>}
    <div className="ws-section-title"><h2>与项目相连的画布 <small>{project.canvasIds.length} 张</small></h2><div className="ws-intro-actions">{isOwner && <><button className="ws-link-button" onClick={() => setPickerOpen(true)}><Layers size={13} />关联已有画布</button><button className="ws-link-button" disabled={busy} onClick={() => void createCanvas()}><Plus size={13} />新建画布</button></>}</div></div><ErrorNotice error={documentError} onRetry={() => void loadDocuments()} />{linked.length ? <div className="ws-grid ws-grid-canvases">{linked.map(document => <Link key={document.id} className="ws-panel ws-canvas-card" to={`/editor/${document.id}`}><div className="ws-canvas-preview">{document.thumbnail ? <img src={document.thumbnail} alt={document.title} /> : <div className="ws-canvas-blank"><Layers size={24} /></div>}</div><div className="ws-canvas-info"><div><h3>{document.title}</h3><p>{timeLabel(document.updatedAt)}</p></div><ArrowUpRight size={14} /></div></Link>)}</div> : <div className="ws-panel"><div className="ws-list-row"><span className="ws-project-mark"><Layers size={17} /></span><div><h3>把设计与需求放在一起</h3><p>关联一张画布，让你和 AI 都能更直观地理解这个项目。</p></div>{isOwner && <button className="ws-button ws-button-small" onClick={() => setPickerOpen(true)}>关联画布</button>}</div></div>}
    {transition && <TransitionDialog event={transition.event} target={transition.patch.status!} onConfirm={confirmTransition} onClose={cancelTransition} />}
    {setupOpen && isOwner && <TableSetupWizard key={`setup:${project.id}`} project={project} members={members} initial={{ roles: [], columns: baseColumnChoices.map(column => ({ key: column.id, label: project.tableConfig?.baseLabels[column.id] || column.label, visible: column.id === 'title' || (project.tableConfig ? project.tableConfig.visibleBaseFields.includes(column.id) : column.initial) })), fields: (project.tableConfig?.customFields ?? []).map(field => ({ ...field, options: field.options ?? [] })) }} onGenerate={generateTable} onClose={() => setSetupOpen(false)} />}
    <div style={{ marginTop: 25 }}><Link className="ws-link-button" to="/projects"><ArrowLeft size={13} />返回项目列表</Link></div>
    {(createOpen || editEvent) && <EventModal key={editEvent?.id ?? 'new'} project={project} event={editEvent ?? undefined} onSave={saveEvent} onRefresh={reload} onWorkflowTransition={async status => { const value = currentProject.current?.events.find(event => event.id === editEvent?.id); if (value && value.status !== status) await askTransition(value, { status }, { expectedEventUpdatedAt: value.updatedAt, baseValues: { status: value.status } }) }} members={members} readOnly={!canEdit} onClose={() => { setCreateOpen(false); setEditEvent(null) }} />}{editProject && isOwner && <ProjectForm project={project} onClose={() => setEditProject(false)} onSave={async (draft, actionId) => { await invoke(current => updateProject(current.id, draft, { revision: current.revision, mutationId: actionId })) }} />}{inviteOpen && isOwner && <ProjectInviteDialog key={`invite:${project.id}`} project={project} onClose={() => { setInviteOpen(false); void reload() }} />}{aiOpen && isOwner && <AIShareDialog kind="management" resourceId={project.id} title={project.name} project={project} documents={documents} onClose={() => setAIOpen(false)} />}{pickerOpen && isOwner && <CanvasPicker project={project} documents={documents} onSave={async ids => { await invoke(current => updateProject(current.id, { canvasIds: ids }, { revision: current.revision })) }} onClose={() => setPickerOpen(false)} />}{deleteTarget && canEdit && <WorkspaceModal title="删除这条事件？" description={deleteTarget.title} onClose={() => setDeleteTarget(null)} busy={busy}><div className="ws-form"><p className="ws-setting-note">事件会从当前列表移除，删除操作会自动记录在项目历史中。</p><div className="ws-modal-actions"><ModalCancelButton /><button className="ws-button ws-button-danger" disabled={busy} onClick={() => void invoke(current => deleteEvent(current.id, deleteTarget.id, { revision: current.revision, expectedEventUpdatedAt: deleteTarget.updatedAt })).then(() => setDeleteTarget(null)).catch(() => {})}><Trash2 size={13} />删除事件</button></div></div></WorkspaceModal>}
  </>
}
