import { useEffect, useRef, useState } from 'react'
import { ArrowRight, Check, FolderOpen, Layers, ShieldCheck } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { getCurrentUser } from '@/services/auth'
import type { AuthUser } from '@/services/auth'
import { acceptProjectInvite, mutationId, previewProjectInvite } from '@/services/management'
import type { ProjectInvitePreview } from '@/types/management'
import { ErrorNotice, timeLabel } from '@/components/workspace/ui'
import '@/components/workspace/workspace.css'

export default function ProjectInvitePage() {
  const { token = '' } = useParams<{ token: string }>(), navigate = useNavigate()
  const [user, setUser] = useState<AuthUser | null>(null), [preview, setPreview] = useState<ProjectInvitePreview | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [retry, setRetry] = useState(0)
  const actionId = useRef(mutationId()), activeToken = useRef(token); activeToken.current = token
  useEffect(() => { let stopped = false; setLoading(true); setBusy(false); setPreview(null); setError(''); setUser(null); actionId.current = mutationId(); void getCurrentUser().then(async result => { if (stopped) return; setUser(result.user); if (result.user) { const value = await previewProjectInvite(token); if (!stopped) setPreview(value) } }).catch(cause => { if (!stopped) setError(cause instanceof Error ? cause.message : '邀请暂时无法读取，请检查链接或重试。') }).finally(() => { if (!stopped) setLoading(false) }); return () => { stopped = true } }, [token, retry])
  const next = `/project-invite/${encodeURIComponent(token)}`
  const authURL = (mode: 'login' | 'register') => `/auth?${new URLSearchParams({ mode, next, projectInviteToken: token })}`
  async function join() { if (!preview || !user || busy) return; const expectedToken = token; setBusy(true); setError(''); try { const project = await acceptProjectInvite(expectedToken, actionId.current); if (activeToken.current === expectedToken) navigate(`/projects/${encodeURIComponent(project.id)}`, { replace: true }) } catch (cause) { if (activeToken.current === expectedToken) setError(cause instanceof Error ? cause.message : '加入尚未确认，可以使用相同邀请重试。') } finally { if (activeToken.current === expectedToken) setBusy(false) } }
  return <div className="ws-shell ws-invite-landing"><Link to="/" className="ws-invite-brand"><span className="ws-logo"><Layers size={22} /></span><strong>FlowBoard</strong><small>共同推进每一件事</small></Link><main className="ws-invite-landing-card"><span className="ws-invite-hero-icon"><FolderOpen size={30} strokeWidth={1.5} /></span><p className="ws-eyebrow">PROJECT INVITATION</p><h1>{preview?.projectName ?? '有人邀请你加入项目'}</h1><p className="ws-page-description">进入同一张问题表格，让分工、处理进度和记录保持同步。</p><ErrorNotice error={error} onRetry={() => setRetry(value => value + 1)} />{loading ? <p className="ws-loading">正在确认邀请与登录状态…</p> : !user ? <><div className="ws-invite-explanation"><ShieldCheck size={19} /><p><strong>先确认你的账号</strong>登录后可以预览项目、邀请权限与角色，再决定是否加入。没有账号时可使用这条项目邀请完成正常邮箱验证注册。</p></div><div className="ws-invite-landing-actions"><Link className="ws-button ws-button-primary" to={authURL('login')}>已有账号，登录 <ArrowRight size={15} /></Link><Link className="ws-button" to={authURL('register')}>邮箱注册后继续</Link></div></> : preview ? <><div className="ws-invite-grant"><div><small>邀请授予的项目权限</small><strong>{preview.permission === 'edit' ? '可编辑问题' : '只读访问'}</strong><p>{preview.permission === 'edit' ? '可以查看、创建和修改项目问题，上传附件。项目设置、邀请和角色管理由创建者负责。' : '可以查看整个项目的问题表格与工作记录。无法修改问题或项目设置。'}</p></div><div><small>加入时分配的角色</small><div className="ws-member-roles">{preview.roles.map(role => <span className="ws-tag" key={role.id} style={{ color: role.color, background: `${role.color}18` }}>{role.name}</span>)}{!preview.roles.length && <span className="ws-setting-note">不预分配角色</span>}</div></div></div><p className="ws-setting-note">当前账号：{user.email}<br />邀请到期 {timeLabel(preview.expiresAt, true)} · 剩余 {preview.remainingUses} 个加入名额<br />角色表示分工，访问权限作用于整个项目表格。项目创建者与所有权保持不变。</p><div className="ws-invite-landing-actions">{preview.accepted ? <Link className="ws-button ws-button-primary" to={`/projects/${encodeURIComponent(preview.projectId)}`}><Check size={15} />你已加入，打开项目</Link> : <button className="ws-button ws-button-primary" disabled={busy || preview.expiresAt <= Date.now() || preview.remainingUses <= 0} onClick={() => void join()}><ArrowRight size={15} />{busy ? '正在加入…' : '确认权限并加入项目'}</button>}<Link className="ws-button" to="/projects">返回我的项目</Link></div></> : <p className="ws-setting-note">当前账号未能读取邀请。链接可能已经撤销、到期或用完名额，请联系项目创建者。</p>}</main><p className="ws-invite-landing-foot">邀请用于加入项目表格。原有画布的分享与编辑权限独立设置。</p></div>
}
