import { useEffect, useRef, useState } from 'react'
import { ArrowRight, BookOpen, Check, CheckCircle2, ChevronUp, Play, X } from 'lucide-react'
import type { ManagementProject } from '@/types/management'
export type GuideAction = 'info' | 'setup' | 'newIssue' | 'table' | 'board' | 'overview' | 'invite' | 'settings' | 'ai'
const steps: Array<{ id: string; title: string; subtitle: string; text: string; example: string; tips: string[]; actions: Array<{ title: string; action: GuideAction }> }> = [
  { id: 'info', title: '写清名称与目标', subtitle: '1 · 给项目一个明确的边界', text: '项目名称说明你在推进什么；目标与说明写清交付结果、范围和验收标准。后续问题会集中放在这一个项目里。', example: '名称：网站需求与问题跟踪。目标：本月发布绘图工作台，先完成移动端适配，验收以手机打开、编辑与分享均可用为准。', tips: ['名称可以随时修改，不必一次想得完美。', '记录目标，不用把每一条问题都塞进项目说明。'], actions: [{ title: '编辑名称与目标', action: 'info' }] },
  { id: 'roles', title: '先创建参与角色', subtitle: '2 · 用角色整理不同人的工作', text: '角色是问题表格上方的标签，例如技术、策划、美工、测试。先建立与你的团队相符的角色，再开始记录；之后可以按角色查看问题和统计。', example: '技术：实现和修复；策划：需求与规则；美工：界面与素材；测试：验收和复现。你也可以只建立一个角色。', tips: ['角色名称和颜色由你定义，已有记录会沿用角色。', '给角色选人表示分工；项目访问权限仍需通过成员设置明确授权。'], actions: [{ title: '创建或调整角色', action: 'setup' }] },
  { id: 'fields', title: '选择字段与字段类型', subtitle: '3 · 让每一列记录有用的信息', text: '保留问题标题，选择是否显示角色、状态、处理人、附件和推送对象。自定义列可使用文本、选项、数字、日期或勾选，也可以指定只适用于某个角色。', example: '版本号 → 文本；平台 → 选项 Windows / Linux / Android；预计工时 → 数字；期望日期 → 日期；可复现 → 勾选。', tips: ['“必填”要求添加问题时提供该字段值，数字 0 和未勾选也是有效值。', '选项字段先填写可选项；列名可以改成你的习惯用语。'], actions: [{ title: '设置表格字段', action: 'setup' }] },
  { id: 'generate', title: '生成角色问题表格', subtitle: '4 · 把设置一次保存下来', text: '在字段向导最后点击“生成问题表格”，角色、列名和自定义字段会一起保存。之后点击角色标签，进入该角色的表格，直接新增一行。', example: '先选择技术角色，再显示问题、平台、优先级、处理状态、处理人和推送对象。', tips: ['向导中的草稿会保留在当前浏览器，跳过后可以继续设置。', '改变字段定义可能影响已有记录，生成前检查适用角色和必填列。'], actions: [{ title: '打开表格设置向导', action: 'setup' }, { title: '查看问题表格', action: 'table' }] },
  { id: 'issue', title: '写下第一条可处理的问题', subtitle: '5 · 标题清楚，描述可执行', text: '点击“新增一行”，写标题、选择角色与处理人，填写必需的自定义列，点击添加或按 Enter。添加后点击详情补充复现步骤、预期结果和附件；单元格修改自动保存。', example: '标题：手机窄屏下工具栏遮挡画布。描述：屏幕宽度 375px；打开编辑页后工具栏盖住右侧画布。期望：收起到菜单按钮，画布保持可触摸。', tips: ['记录人、记录时间和操作历史由服务器自动记录。', '看到保存错误时输入仍保留；先解决冲突或连接问题，再继续。'], actions: [{ title: '新增一行写问题', action: 'newIssue' }, { title: '查看已有记录', action: 'table' }] },
  { id: 'flow', title: '推进、验收与选择推送对象', subtitle: '6 · 分清处理完成与最终完成', text: '按实际结果切换待处理、处理中、等待验收、待发布、已发布与已完成。验收不合格可回到处理中；阻塞、暂缓、取消可单独记录原因。选好接收人后显式点击推送，通知发送到站内收件箱。', example: '技术处理 → 等待测试验收 → 不合格填写“手机触摸仍偏移” → 返工 → 已处理待发布 → 发布 → 最终完成。', tips: ['已发布不是最终完成；阶段时间、耗时和操作人会自动留在记录里。', '填写推送对象不会自动发送，推送通知也不会授予项目访问权限。'], actions: [{ title: '打开问题表格', action: 'table' }, { title: '查看流程看板', action: 'board' }] },
  { id: 'invite', title: '邀请成员并分配角色', subtitle: '7 · 创建者管理访问与分工', text: '创建者可以复制项目邀请链接，选择只读或编辑权限，并预分配角色。对方正常登录或邮箱注册后，预览权限并明确加入；成员设置可再修改权限、角色或移除访问。', example: '邀请测试人员只读查看；给技术成员编辑问题权限并分配技术角色。角色是分工，访问权限作用于整个项目表格。', tips: ['邀请有有效期和名额限制；复制链接后由你自行发送，不自动发邮件。', '删除项目不可恢复；原有独立画布保留，成员和邀请不会转移所有权。'], actions: [{ title: '生成邀请链接', action: 'invite' }, { title: '管理成员与角色', action: 'settings' }] },
  { id: 'insights', title: '看统计，再交给 AI 读取', subtitle: '8 · 从真实记录决定下一步', text: '项目概览显示分类、趋势和推进记录；主工作台选择项目后，可按角色查看十个阶段、停留时长与今天的操作。AI 分享是只读链接，选择当前内容或整个项目后，再复制给你的 AI 工具。', example: '让 AI 整理验收不合格的问题、列出返工顺序；回到表格由你和团队实际修改，不把 AI 链接当作成员邀请。', tips: ['统计来自保存的事件，不会根据引导步骤虚构进度。', 'AI 链接可撤销；整个项目模式会包含以后新增的记录，生成前确认范围。'], actions: [{ title: '查看项目概览', action: 'overview' }, { title: '生成 AI 只读入口', action: 'ai' }] },
]
interface Progress { selected: number; checked: string[]; expanded: boolean; skipped: boolean }
function readProgress(key: string): Progress { try { const value = JSON.parse(localStorage.getItem(key) ?? 'null') as Partial<Progress> | null; if (value) return { selected: Number.isInteger(value.selected) ? Math.max(0, Math.min(steps.length - 1, value.selected ?? 0)) : 0, checked: Array.isArray(value.checked) ? value.checked.filter(id => typeof id === 'string' && steps.some(step => step.id === id)) : [], expanded: value.expanded === true, skipped: value.skipped === true } } catch { /* Browser storage is optional; current state remains usable. */ }; return { selected: 0, checked: [], expanded: false, skipped: false } }
export default function ProjectGuide({ project, userId, openSignal = 0, onAction }: { project: ManagementProject; userId: string; openSignal?: number; onAction: (action: GuideAction) => void }) {
  const storageKey = `flowboard.project-guide.v1:${userId}:${project.id}`
  const [progress, setProgress] = useState<Progress>(() => readProgress(storageKey)), [storageError, setStorageError] = useState(false)
  const lastSignal = useRef(0)
  useEffect(() => { if (openSignal && openSignal !== lastSignal.current) { lastSignal.current = openSignal; setProgress(previous => ({ ...previous, expanded: true, skipped: false })) } }, [openSignal])
  useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify(progress)); setStorageError(false) } catch { setStorageError(true) } }, [storageKey, progress])
  const step = steps[progress.selected] ?? steps[0]!
  const available = (id: string) => id === 'info' ? true : id === 'roles' ? project.roles.length > 0 : id === 'fields' || id === 'generate' ? project.tableConfig?.configured === true : id === 'issue' ? project.events.length > 0 : id === 'invite' ? Boolean(project.members?.length) : false
  function toggleComplete() { setProgress(previous => ({ ...previous, checked: previous.checked.includes(step.id) ? previous.checked.filter(id => id !== step.id) : [...previous.checked, step.id] })) }
  return <section className={`ws-guide ${progress.expanded ? 'expanded' : ''}`} aria-label="项目使用引导"><div className="ws-guide-head"><span className="ws-start-guide-icon"><BookOpen size={19} /></span><div><h3>项目使用引导</h3><p>{progress.skipped ? '已暂时跳过，随时可以从上一步继续。' : `从创建到协作 · 你已标记 ${progress.checked.length} / ${steps.length} 步完成`}</p></div><button className="ws-button ws-button-small" onClick={() => setProgress(previous => ({ ...previous, expanded: !previous.expanded, skipped: false }))}>{progress.expanded ? <ChevronUp size={13} /> : <Play size={12} />}{progress.expanded ? '收起引导' : progress.skipped ? '继续引导' : '打开引导'}</button>{progress.expanded && <button className="ws-icon-button" aria-label="暂时跳过项目引导，保留进度" onClick={() => setProgress(previous => ({ ...previous, expanded: false, skipped: true }))}><X size={14} /></button>}</div>{progress.expanded && <div className="ws-guide-body"><nav className="ws-guide-steps" aria-label="创建与使用步骤">{steps.map((value, index) => <button key={value.id} className={index === progress.selected ? 'active' : ''} aria-current={index === progress.selected ? 'step' : undefined} onClick={() => setProgress(previous => ({ ...previous, selected: index }))}><span>{progress.checked.includes(value.id) ? <Check size={12} /> : index + 1}</span><strong>{value.title}</strong>{available(value.id) && <small title="项目已有对应的真实数据">已有数据</small>}</button>)}</nav><div className="ws-guide-detail"><p className="ws-eyebrow">{step.subtitle}</p><h3>{step.title}</h3><p>{step.text}</p><div className="ws-guide-example"><strong>写法示例</strong><p>{step.example}</p></div><ul>{step.tips.map(tip => <li key={tip}>{tip}</li>)}</ul><div className="ws-guide-actions">{step.actions.map(action => <button key={action.action} className="ws-button ws-button-small" onClick={() => onAction(action.action)}>{action.title}<ArrowRight size={12} /></button>)}</div><div className="ws-guide-progress-actions"><button className="ws-link-button" onClick={toggleComplete}><CheckCircle2 size={14} />{progress.checked.includes(step.id) ? '取消此步骤标记' : '我已了解 / 完成此步骤'}</button><button className="ws-button ws-button-small ws-button-primary" disabled={progress.selected >= steps.length - 1} onClick={() => setProgress(previous => ({ ...previous, selected: Math.min(steps.length - 1, previous.selected + 1) }))}>下一步<ArrowRight size={12} /></button></div><p className="ws-setting-note">引导勾选仅记录你的学习进度，不会创建事件、改变问题状态或发送通知。{storageError ? '当前浏览器无法保存引导进度；页面内仍可继续使用。' : '进度保存在当前浏览器，可以收起、跳过或稍后继续。'}</p></div></div>}</section>
}
