import { useEffect, useRef, useState } from 'react'
import { ArrowRight, BookOpen, Check, Plus } from 'lucide-react'
import { mutationId } from '@/services/management'
import type { ManagementProject, ProjectDraft } from '@/types/management'
import { ErrorNotice, ModalCancelButton, WorkspaceModal } from '@/components/workspace/ui'
const colors = ['#7963e9', '#35a58b', '#6794df', '#d99b53', '#ce718d', '#64748b']
function restoredDraft(key: string): { draft: Pick<ProjectDraft, 'name' | 'description' | 'color'>; actionId: string } | null {
  try { const value = JSON.parse(localStorage.getItem(key) ?? 'null') as { draft?: Record<string, unknown>; actionId?: unknown } | null; if (value?.draft && typeof value.draft.name === 'string' && typeof value.draft.description === 'string' && typeof value.draft.color === 'string' && /^#[0-9a-f]{6}$/i.test(value.draft.color) && typeof value.actionId === 'string') return { draft: { name: value.draft.name, description: value.draft.description, color: value.draft.color }, actionId: value.actionId } } catch { /* Keep normal form usable when storage is unavailable. */ }; return null
}
export default function ProjectForm({ project, userId, firstProject = false, onSave, onClose }: { project?: ManagementProject; userId?: string; firstProject?: boolean; onSave: (draft: ProjectDraft, actionId: string) => Promise<void>; onClose: () => void }) {
  const draftKey = userId ? `flowboard.project-create-draft.v1:${userId}` : null
  const restored = useRef(!project && draftKey ? restoredDraft(draftKey) : null)
  const initial = project ? { name: project.name, description: project.description, color: project.color } : restored.current?.draft ?? { name: '', description: '', color: colors[0] ?? '#7963e9' }
  const [form, setForm] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState(''), [storageError, setStorageError] = useState(false)
  const original = useRef(JSON.stringify(initial)), actionId = useRef(restored.current?.actionId ?? mutationId()), working = useRef(false)
  useEffect(() => { if (project || !draftKey) return; try { localStorage.setItem(draftKey, JSON.stringify({ draft: form, actionId: actionId.current })); setStorageError(false) } catch { setStorageError(true) } }, [form, draftKey, project?.id])
  async function submit(event: React.FormEvent) { event.preventDefault(); if (working.current) return; if (!form.name.trim()) { setError('请为项目填写名称。'); return }; working.current = true; setBusy(true); setError(''); try { await onSave({ ...form, name: form.name.trim() }, actionId.current); if (!project && draftKey) { try { localStorage.removeItem(draftKey) } catch { /* Successful server save still takes priority. */ } }; onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : '项目保存失败，名称和目标草稿仍保留。') } finally { working.current = false; setBusy(false) } }
  return <WorkspaceModal title={project ? '编辑项目信息' : firstProject ? '创建第一个项目：先写清目标' : '开启新项目：先写清目标'} description={project ? '让设计、需求和每一步进展拥有清晰的归属。' : '先填写名称和目标，创建后接着设置角色与表格字段。每一步都有说明，可以跳过再继续。'} onClose={onClose} busy={busy} dirty={(Boolean(project) || storageError) && JSON.stringify(form) !== original.current}><form className="ws-form" onSubmit={event => void submit(event)}><ErrorNotice error={error} />{!project && <div className="ws-create-guide"><BookOpen size={18} /><div><strong>{restored.current?.draft.name ? '继续上次的新建草稿' : '名称回答“做什么”，目标回答“做到什么算完成”'}</strong><p>例如：名称「网站需求与问题跟踪」；目标「本月完成移动端适配，手机能正常绘图、编辑和分享」。之后可按技术、策划、美工等角色记录问题。</p><small>{storageError ? '当前浏览器无法保存草稿，关闭前请保留输入内容。' : '名称、目标和颜色草稿会保留在当前浏览器；现在取消，之后可以继续。'}</small></div></div>}<div className="ws-field"><label htmlFor="project-name">项目名称 <span className="ws-required">*</span></label><input id="project-name" autoFocus maxLength={120} value={form.name} placeholder="例如：网站需求与问题跟踪" onChange={event => setForm(previous => ({ ...previous, name: event.target.value }))} required /><small>用一眼能认出的名称，稍后可由创建者修改。</small></div><div className="ws-field"><label htmlFor="project-description">目标与验收说明（可后补）</label><textarea id="project-description" value={form.description} rows={5} placeholder="想解决什么？希望交付什么？如何判断已完成？
例如：完成移动端适配，验收以手机打开、绘图、编辑和分享均可用为准。" onChange={event => setForm(previous => ({ ...previous, description: event.target.value }))} /><small>描述项目范围与验收标准。每条具体问题放入后面的表格。</small></div><div className="ws-field"><span>项目颜色</span><div className="ws-color-palette">{colors.map(color => <button type="button" key={color} style={{ backgroundColor: color }} aria-label={`选择项目颜色 ${color}`} aria-pressed={form.color === color} className={form.color === color ? 'active' : ''} onClick={() => setForm(previous => ({ ...previous, color }))} />)}<input className="ws-color-input" type="color" aria-label="自定义项目颜色" value={form.color} onChange={event => setForm(previous => ({ ...previous, color: event.target.value }))} /></div></div>{!project && <ol className="ws-create-next"><li>填写名称与目标</li><li>创建角色</li><li>选字段，生成表格</li><li>直接写问题，再协作推进</li></ol>}<div className="ws-modal-actions"><ModalCancelButton label={project ? '取消' : '稍后继续（保留草稿）'} /><button className="ws-button ws-button-primary" disabled={busy || !form.name.trim()} type="submit">{project ? <Check size={14} /> : <Plus size={14} />}{busy ? '正在保存…' : project ? '保存修改' : '创建项目，继续设置角色'}{!project && <ArrowRight size={12} />}</button></div></form></WorkspaceModal>
}
