import { useRef, useState } from 'react'
import { Check, Plus } from 'lucide-react'
import { mutationId } from '@/services/management'
import type { ManagementProject, ProjectDraft } from '@/types/management'
import { ErrorNotice, ModalCancelButton, WorkspaceModal } from '@/components/workspace/ui'
const colors = ['#7963e9', '#35a58b', '#6794df', '#d99b53', '#ce718d', '#64748b']
export default function ProjectForm({ project, onSave, onClose }: { project?: ManagementProject; onSave: (draft: ProjectDraft, actionId: string) => Promise<void>; onClose: () => void }) {
  const initial = { name: project?.name ?? '', description: project?.description ?? '', color: project?.color ?? colors[0] ?? '#7963e9' }
  const [form, setForm] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const original = useRef(JSON.stringify(initial)), actionId = useRef(mutationId())
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.name.trim()) { setError('请为项目填写名称。'); return }; setBusy(true); setError(''); try { await onSave({ ...form, name: form.name.trim() }, actionId.current); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : '项目保存失败') } finally { setBusy(false) } }
  return <WorkspaceModal title={project ? '编辑项目信息' : '开启一个新的项目'} description="让设计、需求和每一步进展拥有清晰的归属。" onClose={onClose} busy={busy} dirty={JSON.stringify(form) !== original.current}><form className="ws-form" onSubmit={event => void submit(event)}><ErrorNotice error={error} /><div className="ws-field"><label htmlFor="project-name">项目名称</label><input id="project-name" autoFocus maxLength={120} value={form.name} placeholder="给项目一个清晰的名字" onChange={event => setForm(previous => ({ ...previous, name: event.target.value }))} required /></div><div className="ws-field"><label htmlFor="project-description">目标与说明</label><textarea id="project-description" value={form.description} rows={5} placeholder="想解决什么问题？希望达到怎样的结果？" onChange={event => setForm(previous => ({ ...previous, description: event.target.value }))} /></div><div className="ws-field"><span>项目颜色</span><div className="ws-color-palette">{colors.map(color => <button type="button" key={color} style={{ backgroundColor: color }} aria-label={`选择项目颜色 ${color}`} aria-pressed={form.color === color} className={form.color === color ? 'active' : ''} onClick={() => setForm(previous => ({ ...previous, color }))} />)}<input className="ws-color-input" type="color" aria-label="自定义项目颜色" value={form.color} onChange={event => setForm(previous => ({ ...previous, color: event.target.value }))} /></div></div><div className="ws-modal-actions"><ModalCancelButton /><button className="ws-button ws-button-primary" disabled={busy || !form.name.trim()} type="submit">{project ? <Check size={14} /> : <Plus size={14} />}{busy ? '正在保存…' : project ? '保存修改' : '创建项目'}</button></div></form></WorkspaceModal>
}
