import { useState } from 'react'
import { ArrowRight, Check, Clock3 } from 'lucide-react'
import type { ManagementEvent, ManagementHistory, ManagementStatus } from '@/types/management'
import { ErrorNotice, ModalCancelButton, WorkspaceModal, timeLabel } from '@/components/workspace/ui'
import { durationLabel, statusName, statuses } from './model'
const pipeline: ManagementStatus[] = ['todo', 'doing', 'review', 'ready', 'released', 'done']
export class TransitionCancelled extends Error { constructor() { super('阶段切换已取消，原状态保留。'); this.name = 'TransitionCancelled' } }
export function TransitionDialog({ event, target, onConfirm, onClose }: { event: ManagementEvent; target: ManagementStatus; onConfirm: (note: string) => Promise<void>; onClose: () => void }) {
  const [note, setNote] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const required = ['rejected', 'blocked', 'on_hold', 'cancelled'].includes(target)
  async function submit() { if (required && !note.trim()) { setError('请填写原因，便于接下来的处理和追溯。'); return }; setBusy(true); setError(''); try { await onConfirm(note.trim()); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : '阶段变更未保存；说明仍保留。') } finally { setBusy(false) } }
  return <WorkspaceModal title={`切换为「${statusName(target)}」`} description={event.title} onClose={onClose} dirty={Boolean(note)} busy={busy}><div className="ws-form"><div className="ws-transition-summary"><span className={`ws-tag ws-status-${event.status}`}>{statusName(event.status)}</span><ArrowRight size={15} /><span className={`ws-tag ws-status-${target}`}>{statusName(target)}</span></div><ErrorNotice error={error} /><div className="ws-field"><label htmlFor="workflow-reason">{target === 'rejected' ? '验收不合格的原因' : '本次阶段说明'}{required ? ' *' : '（可选）'}</label><textarea id="workflow-reason" rows={5} maxLength={2000} value={note} onChange={value => setNote(value.target.value)} placeholder={target === 'rejected' ? '哪些结果不符合要求？需要怎样返工？' : '说明当前结果、待确认事项或下一步要求…'} /><small>说明会进入永久操作记录；时间、阶段耗时与操作人由系统自动记录。</small></div><div className="ws-modal-actions"><ModalCancelButton /><button className="ws-button ws-button-primary" disabled={busy || (required && !note.trim())} onClick={() => void submit()}><Check size={14} />{busy ? '保存中…' : '确认阶段变更'}</button></div></div></WorkspaceModal>
}
export function WorkflowStatus({ event, history, onSelect, readOnly = false }: { event: ManagementEvent; history: ManagementHistory[]; onSelect?: (status: ManagementStatus) => void; readOnly?: boolean }) {
  const visited = new Set<ManagementStatus>([event.status])
  for (const item of history) for (const change of item.changes) { if (change.field === 'status') { if (statuses.some(status => status.id === change.before)) visited.add(change.before as ManagementStatus); if (statuses.some(status => status.id === change.after)) visited.add(change.after as ManagementStatus) } }
  return <section className="ws-workflow-detail"><div className="ws-section-title"><h2>处理流程</h2><span className={`ws-tag ws-status-${event.status}`}>{statusName(event.status)}</span></div><div className="ws-flow-stepper">{pipeline.map((status, index) => <button key={status} className={`ws-flow-step ${event.status === status ? 'current' : visited.has(status) ? 'visited' : ''}`} disabled={readOnly || !onSelect || event.status === status} onClick={() => onSelect?.(status)} title={visited.has(status) ? '真实记录中出现过这个阶段' : '尚未记录这个阶段'}><span>{visited.has(status) ? <Check size={12} /> : index + 1}</span><strong>{statusName(status)}</strong></button>)}</div><div className="ws-flow-exceptions">{statuses.filter(status => !pipeline.includes(status.id)).map(status => <button key={status.id} className={`ws-tag ws-status-${status.id}`} disabled={readOnly || !onSelect || event.status === status.id} onClick={() => onSelect?.(status.id)}>{status.name}</button>)}</div><div className="ws-workflow-facts"><p><Clock3 size={12} />{event.stageChangedAt ? `进入当前阶段：${timeLabel(event.stageChangedAt, true)}` : '阶段开始时间尚未记录'}</p>{event.stageTimes?.doing !== undefined && <p>已结束处理阶段累计：{durationLabel(event.stageTimes.doing)}</p>}</div>{event.transitionNote && <div className="ws-stage-note"><strong>当前阶段说明</strong><p>{event.transitionNote}</p></div>}</section>
}
