import { useEffect, useState } from 'react'
import { Bug, Check, Code2, ExternalLink, Link2, Palette, RefreshCw, Sparkles, Trash2, Wrench } from 'lucide-react'
import { createAIShare, getAIShares, revokeAIShare } from '@/services/management'
import type { AIShare, ManagementProject } from '@/types/management'
import type { StoredDocument } from '@/utils/storage'
import { CopyButton, ErrorNotice, WorkspaceModal, timeLabel } from './ui'

const presets = [
  { id: 'design', title: '基于画布设计 UI', icon: Palette, text: '请读取项目目标、关联画布和所选事件，基于设计实现清晰、精致且响应式的 UI。保留已有业务与数据，先说明实施范围，再完成开发和验证。' },
  { id: 'develop', title: '按需求开发', icon: Code2, text: '请读取需求描述、优先级和关联设计，按未完成事件逐项实现。保留已有行为，完成必要的功能验证，并列出完成项与待确认项。' },
  { id: 'fix', title: '按问题修复', icon: Bug, text: '请读取问题描述、附件和操作历史，先核实具体原因，再最小范围修复。验证复现步骤和相邻功能，不把未验证的结果标为通过。' },
  { id: 'maintain', title: '维护已有项目', icon: Wrench, text: '请读取项目目标、设计与历史，理解现有约束后继续维护。保留既有账号、数据和功能，优先处理当前未完成事件。' },
  { id: 'progress', title: '整理项目进度', icon: Check, text: '请根据真实事件、优先级、完成记录与统计整理项目进度，列出当前阻碍、下一步安排与需要人工决定的事项。不要生成示例进度或虚构完成情况。' },
]
function absolute(value: string) { return new URL(value, window.location.origin).href }
export default function AIShareDialog({ kind, resourceId, title, project, documents = [], onClose }: { kind: 'management' | 'canvas'; resourceId: string; title: string; project?: ManagementProject; documents?: StoredDocument[]; onClose: () => void }) {
  const [links, setLinks] = useState<AIShare[]>([])
  const [scopeMode, setScopeMode] = useState<'selected' | 'live'>('selected')
  const [eventIds, setEventIds] = useState<string[]>(project?.events.map(event => event.id) ?? [])
  const [canvasIds, setCanvasIds] = useState<string[]>(project?.canvasIds ?? [resourceId])
  const [history, setHistory] = useState(true), [stats, setStats] = useState(true), [attachments, setAttachments] = useState(true), [preview, setPreview] = useState(true)
  const [preset, setPreset] = useState('develop'), [error, setError] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false)
  async function load() { setLoading(true); try { setLinks(await getAIShares(kind, resourceId)); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : '读取链接失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [kind, resourceId])
  async function create() { setBusy(true); setError(''); try { const link = await createAIShare(kind, resourceId, { ...(kind === 'management' && scopeMode === 'live' ? {} : { canvasIds: kind === 'canvas' ? [resourceId] : canvasIds, eventIds: kind === 'management' ? eventIds : [] }), includeHistory: kind === 'management' && history, includeStats: kind === 'management' && stats, includeAttachments: attachments, includePreview: preview }); setLinks(previous => [link, ...previous]) } catch (cause) { setError(cause instanceof Error ? cause.message : '创建读取链接失败') } finally { setBusy(false) } }
  async function revoke(id: string) { setBusy(true); try { await revokeAIShare(id); setLinks(previous => previous.filter(link => link.id !== id)) } catch (cause) { setError(cause instanceof Error ? cause.message : '撤销链接失败') } finally { setBusy(false) } }
  const prompt = (link: AIShare) => `请先读取这个只读入口：${absolute(link.url)}\n结构化数据：${absolute(link.jsonUrl)}\n\n${presets.find(item => item.id === preset)?.text ?? ''}\n此链接仅提供所选内容的读取权限；网站修改与命令执行需另行授权。`
  const toggle = (values: string[], value: string) => values.includes(value) ? values.filter(item => item !== value) : [...values, value]
  return <WorkspaceModal title="交给 AI，接着推进" description={title} onClose={onClose} busy={busy} wide><div className="ws-form"><div className="ws-ai-intro"><Sparkles size={23} /><div><strong>一个链接，读懂设计与需求</strong><p>AI 可直接读取 Markdown 与 JSON，无需登录。链接只开放下方选定内容，你可以随时撤销。</p></div></div><ErrorNotice error={error} />
    {project && <div className="ws-ai-scope"><label className="ws-choice-row"><input className="ws-check" type="radio" name="ai-scope-mode" checked={scopeMode === 'selected'} onChange={() => setScopeMode('selected')} /><span>仅当前勾选内容<small>链接只包含选定事件与画布，之后新增内容不会自动开放。</small></span></label><label className="ws-choice-row"><input className="ws-check" type="radio" name="ai-scope-mode" checked={scopeMode === 'live'} onChange={() => setScopeMode('live')} /><span>整个项目，持续读取<small>包含之后新增的事件与关联画布；此选择会持续开放整个项目范围。</small></span></label></div>}{project && scopeMode === 'selected' && <><div className="ws-section-title"><h2>选择事件 <small>{eventIds.length} / {project.events.length}</small></h2><button className="ws-link-button" onClick={() => setEventIds(eventIds.length === project.events.length ? [] : project.events.map(event => event.id))}>{eventIds.length === project.events.length ? '取消全选' : '全部选择'}</button></div><div className="ws-ai-scope">{project.events.length ? project.events.map(event => <label className="ws-choice-row" key={event.id}><input className="ws-check" type="checkbox" checked={eventIds.includes(event.id)} onChange={() => setEventIds(previous => toggle(previous, event.id))} /><span>{event.title}<small>{event.description.slice(0, 70) || '没有补充描述'}</small></span></label>) : <p className="ws-setting-note">项目暂时没有事件。</p>}</div><div className="ws-section-title"><h2>关联画布 <small>{canvasIds.length} 个</small></h2></div><div className="ws-ai-scope">{project.canvasIds.map(id => <label className="ws-choice-row" key={id}><input className="ws-check" type="checkbox" checked={canvasIds.includes(id)} onChange={() => setCanvasIds(previous => toggle(previous, id))} /><span>{documents.find(document => document.id === id)?.title ?? '关联画布'}</span></label>)}{!project.canvasIds.length && <p className="ws-setting-note">关联画布后，可一起分享设计内容。</p>}</div></>}
    <div className="ws-form-grid"><div><label className="ws-choice-row"><input className="ws-check" type="checkbox" checked={attachments} onChange={event => setAttachments(event.target.checked)} /><span>允许读取所选内容的附件</span></label><label className="ws-choice-row"><input className="ws-check" type="checkbox" checked={preview} onChange={event => setPreview(event.target.checked)} /><span>包含画布预览图</span></label></div>{project && <div><label className="ws-choice-row"><input className="ws-check" type="checkbox" checked={history} onChange={event => setHistory(event.target.checked)} /><span>包含操作与完成记录</span></label><label className="ws-choice-row"><input className="ws-check" type="checkbox" checked={stats} onChange={event => setStats(event.target.checked)} /><span>包含所选范围的统计</span></label></div>}</div>
    <div className="ws-modal-actions"><span>{scopeMode === 'live' && project ? '整个项目范围，包括之后新增内容。' : '未选事件或画布不会开放读取。'}</span><button className="ws-button ws-button-primary" disabled={busy} onClick={() => void create()}><Link2 size={15} />{busy ? '处理中…' : '生成只读链接'}</button></div><div className="ws-section-title"><h2>让 AI 做什么</h2></div><div className="ws-prompt-grid">{presets.map(item => <button className={`ws-prompt-option ${preset === item.id ? 'active' : ''}`} key={item.id} onClick={() => setPreset(item.id)}><item.icon size={15} />{item.title}</button>)}</div><div className="ws-section-title"><h2>已授权的读取链接 <small>{links.length}</small></h2><button className="ws-icon-button" aria-label="刷新读取链接" disabled={busy} onClick={() => void load()}><RefreshCw size={15} /></button></div>
    {loading ? <p className="ws-setting-note">正在加载链接…</p> : !links.length ? <p className="ws-setting-note">生成链接后，可以复制入口或带任务说明的完整提示词。</p> : links.map(link => <div className="ws-share-link" key={link.id}><div className="ws-share-link-top"><span className="ws-tag ws-status-done">只读授权</span><span className="ws-saved-note">{timeLabel(link.createdAt)}</span></div><p>{absolute(link.url)}</p><p>{kind === 'management' && link.scope.eventIds === undefined && link.scope.canvasIds === undefined ? '整个项目 · 包含后续新增内容' : `限定范围 · ${link.scope.eventIds?.length ?? 0} 个事件 · ${link.scope.canvasIds?.length ?? (kind === 'canvas' ? 1 : 0)} 张画布`}</p><div className="ws-share-link-actions"><CopyButton text={absolute(link.url)} label="复制读取链接" /><CopyButton text={prompt(link)} label="复制链接与提示词" /><a className="ws-button ws-button-small" href={absolute(link.url)} target="_blank" rel="noreferrer"><ExternalLink size={13} />预览</a><button className="ws-icon-button" disabled={busy} aria-label="撤销此 AI 读取链接" title="撤销此 AI 读取链接" onClick={() => void revoke(link.id)}><Trash2 size={14} /></button></div></div>)}
  </div></WorkspaceModal>
}
