import { useEffect, useRef, useState } from 'react'
import { ChevronDown, Search, Users } from 'lucide-react'
import type { ManagementMember } from '@/types/management'
export default function MemberPicker({ members, selected, onChange, disabled = false, label = '选择接收人' }: { members: ManagementMember[]; selected: string[]; onChange: (ids: string[]) => void; disabled?: boolean; label?: string }) {
  const [open, setOpen] = useState(false), [search, setSearch] = useState(''), [position, setPosition] = useState({ left: 0, top: 0 })
  const root = useRef<HTMLDivElement>(null), button = useRef<HTMLButtonElement>(null)
  useEffect(() => { if (!open) return; function outside(event: MouseEvent) { if (!root.current?.contains(event.target as Node)) setOpen(false) }; function scroll(event: Event) { if (!root.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', outside); window.addEventListener('scroll', scroll, true); return () => { document.removeEventListener('mousedown', outside); window.removeEventListener('scroll', scroll, true) } }, [open])
  function toggle() { if (disabled) return; const box = button.current?.getBoundingClientRect(); if (box) setPosition({ left: Math.max(12, Math.min(box.left, window.innerWidth - 292)), top: Math.max(12, Math.min(box.bottom + 6, window.innerHeight - 330)) }); setOpen(value => !value) }
  const names = selected.map(id => members.find(member => member.id === id)?.name ?? '已选成员')
  const visible = members.filter(member => `${member.name} ${member.emailMasked}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="ws-member-picker" ref={root}><button ref={button} type="button" className="ws-member-trigger" aria-label={label} aria-expanded={open} disabled={disabled} onClick={toggle}><Users size={12} /><span>{names.length ? names.length <= 2 ? names.join('、') : `${names[0]} 等 ${names.length} 人` : label}</span><ChevronDown size={11} /></button>{open && <div className="ws-member-popover" style={{ left: position.left, top: position.top }} onKeyDown={event => { if (event.key === 'Escape') { event.stopPropagation(); setOpen(false); button.current?.focus() } }}><div className="ws-search"><Search size={13} /><input autoFocus aria-label="搜索通知接收人" placeholder="搜索成员…" value={search} onChange={event => setSearch(event.target.value)} /></div><p>从已注册成员中选择。推送通过站内通知送达。</p><div className="ws-member-options">{visible.map(member => <label className="ws-choice-row" key={member.id}><input className="ws-check" type="checkbox" checked={selected.includes(member.id)} disabled={disabled} onChange={() => onChange(selected.includes(member.id) ? selected.filter(id => id !== member.id) : [...selected, member.id])} /><span>{member.name}{member.isSelf && <small className="ws-member-self">我</small>}<small>{member.emailMasked}</small></span></label>)}{!visible.length && <p className="ws-setting-note">没有匹配的注册成员。</p>}</div><div className="ws-member-footer"><span>已选择 {selected.length} 人</span>{selected.length > 0 && <button className="ws-link-button" type="button" disabled={disabled} onClick={() => onChange([])}>清空</button>}<button className="ws-link-button" type="button" onClick={() => setOpen(false)}>完成选择</button></div></div>}</div>
}
