import { useEffect, useRef, useState } from 'react'
import { ArrowDownWideNarrow, ArrowRight, ArrowUpRight, CheckCircle2, Clock3, FileText, FolderOpen, Layers, Plus, Search, Share2, Sparkles, Trash2, Undo2 } from 'lucide-react'
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import ShareDialog from '@/components/editor/ShareDialog'
import ProjectDashboard from '@/components/workspace/ProjectDashboard'
import { useShanghaiToday } from '@/components/workspace/useToday'
import AIShareDialog from '@/components/workspace/AIShareDialog'
import { EmptyState, ErrorNotice, PageIntro, timeLabel } from '@/components/workspace/ui'
import { useWorkspace } from '@/components/workspace/WorkspaceShell'
import { listProjects } from '@/services/management'
import type { ManagementProjectSummary } from '@/types/management'
import { deleteDocument, deleteDocumentForever, generateId, getAllDocuments, getTrashDocuments, restoreDocument, saveDocument } from '@/utils/storage'
import type { StoredDocument } from '@/utils/storage'

export default function HomePage() {
  const { user } = useWorkspace()
  const navigate = useNavigate(), location = useLocation()
  const [params, setParams] = useSearchParams()
  const canvasOnly = location.pathname === '/canvases'
  const trashOpen = params.get('trash') === '1'
  const [documents, setDocuments] = useState<StoredDocument[]>([])
  const [trash, setTrash] = useState<Array<StoredDocument & { deletedAt: number }>>([])
  const [projects, setProjects] = useState<ManagementProjectSummary[]>([])
  const [loading, setLoading] = useState(true), [projectError, setProjectError] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [search, setSearch] = useState(''), [sortDesc, setSortDesc] = useState(true)
  const [shareId, setShareId] = useState<string | null>(null), [aiDocument, setAIDocument] = useState<StoredDocument | null>(null)
  const dayKey = useShanghaiToday()
  const autoCreate = useRef(false)
  async function load() { setLoading(true); setError(''); const results = await Promise.allSettled([getAllDocuments(), getTrashDocuments(), listProjects()]); const docs = results[0], deleted = results[1], management = results[2]; if (docs?.status === 'fulfilled') setDocuments(docs.value); else if (docs?.status === 'rejected') setError(docs.reason instanceof Error ? docs.reason.message : '画布加载失败'); if (deleted?.status === 'fulfilled') setTrash(deleted.value); if (management?.status === 'fulfilled') { setProjects(management.value); setProjectError('') } else setProjectError('项目统计暂时不可用'); setLoading(false) }
  useEffect(() => { void load() }, [dayKey])
  useEffect(() => { const focus = () => { void load() }; window.addEventListener('focus', focus); return () => window.removeEventListener('focus', focus) }, [])
  async function createCanvas() { setBusy(true); try { const id = generateId(), now = Date.now(); await saveDocument({ id, title: '未命名画布', content: '', createdAt: now, updatedAt: now }); navigate(`/editor/${id}`) } catch (cause) { setError(cause instanceof Error ? cause.message : '画布创建失败') } finally { setBusy(false) } }
  useEffect(() => { if (canvasOnly && params.get('create') === '1' && !autoCreate.current) { autoCreate.current = true; setParams({}, { replace: true }); void createCanvas() } }, [params])
  async function remove(id: string) { setBusy(true); try { await deleteDocument(id); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : '移至回收站失败') } finally { setBusy(false) } }
  async function restore(id: string) { setBusy(true); try { await restoreDocument(id); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : '恢复失败') } finally { setBusy(false) } }
  async function removeForever(id: string) { setBusy(true); try { await deleteDocumentForever(id); setTrash(previous => previous.filter(document => document.id !== id)) } catch (cause) { setError(cause instanceof Error ? cause.message : '彻底删除失败') } finally { setBusy(false) } }
  const shown = [...documents].filter(document => document.title.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sortDesc ? b.updatedAt - a.updatedAt : a.updatedAt - b.updatedAt)
  const businessProjects = projects.filter(project => !project.isExample)
  const totals = businessProjects.reduce((sum, project) => {
    const activeTotal = project.stats.activeTotal ?? Math.max(0, (project.stats.total ?? project.eventCount) - (project.stats.cancelled ?? 0))
    const done = project.stats.done ?? 0
    return { pending: sum.pending + Math.max(0, activeTotal - done), done: sum.done + done }
  }, { pending: 0, done: 0 })
  return <><PageIntro eyebrow={canvasOnly ? 'CREATIVE SPACE' : 'YOUR WORKSPACE'} title={canvasOnly ? '我的画布' : `${user.email.split('@')[0]}，欢迎回来`} description={canvasOnly ? '保存灵感，连接设计。你的画布和分享链接都在这里。' : '让设计、需求和每一步进展，在同一个空间井然有序。'}><button className="ws-button ws-button-primary" disabled={busy} onClick={() => void createCanvas()}><Plus size={15} />新建画布</button></PageIntro><ErrorNotice error={error} onRetry={() => void load()} />
    {!canvasOnly && <><div className="ws-stat-grid">{[{ label: '我的画布', value: documents.length, icon: Layers, color: '', caption: '随时继续你的设计' }, { label: '工作项目', value: projectError ? '—' : businessProjects.length, icon: FolderOpen, color: 'teal', caption: projectError || '业务项目，不包含示例' }, { label: '待推进事件', value: projectError ? '—' : totals.pending, icon: Clock3, color: 'amber', caption: '所有尚未完成的有效事项' }, { label: '已完成事件', value: projectError ? '—' : totals.done, icon: CheckCircle2, color: 'blue', caption: '每次完成，自动留下记录' }].map(card => <div className="ws-stat-card" key={card.label}><div className="ws-stat-top"><span>{card.label}</span><span className={`ws-stat-icon ${card.color}`}><card.icon size={15} /></span></div><strong className="ws-stat-value">{loading ? '…' : card.value}</strong><span className="ws-stat-caption">{card.caption}</span></div>)}</div><div className="ws-welcome-band"><div><h2>从一张画布，到一个完整的项目</h2><p>把想法画下来，让问题和需求有归属。<br />通过只读链接，让 AI 读懂你的设计并继续推进。</p><Link className="ws-link-button" to="/projects" style={{ marginTop: 13 }}>打开项目空间 <ArrowRight size={13} /></Link></div><div className="ws-welcome-art" aria-hidden="true"><i /><i /><i /></div></div><div className="ws-section-title"><h2>最近的项目 <small>{projects.length} 个</small></h2><Link className="ws-link-button" to="/projects">查看全部 <ArrowUpRight size={13} /></Link></div>{projectError ? <ErrorNotice error={projectError} onRetry={() => void load()} /> : !loading && !projects.length ? <div className="ws-panel"><EmptyState title="给下一步，一个清晰的归属" description="创建一个项目，记录需求与问题，再关联你的设计画布。"><Link className="ws-button" to="/projects?create=1"><Plus size={14} />创建第一个项目</Link></EmptyState></div> : <div className="ws-grid">{projects.slice(0, 3).map(project => <Link className="ws-panel ws-project-card" to={`/projects/${project.id}`} key={project.id}><div className="ws-project-card-top"><span className="ws-project-mark" style={{ background: `${project.color}18`, color: project.color }}>{project.name.slice(0, 1)}</span><ArrowUpRight size={16} style={{ color: 'var(--ws-muted)' }} /></div><h3>{project.name}{project.isExample && <span className="ws-tag ws-example-badge">示例</span>}</h3><p>{project.description || '在这里连接设计、需求和进度。'}</p><div className="ws-project-meta"><span>{project.eventCount} 个事件</span><span>{project.stats.completionPercent}% 完成</span></div><div className="ws-progress"><span style={{ width: `${project.stats.completionPercent}%`, background: project.color }} /></div><div className="ws-project-card-bottom"><span>更新于 {timeLabel(project.updatedAt)}</span><span>{project.canvasIds.length} 张画布</span></div></Link>)}</div>}</>}
    {!canvasOnly && <ProjectDashboard projects={projects} />}
    <div className="ws-section-title"><h2>{canvasOnly ? '所有画布' : '最近的画布'} <small>{documents.length} 张</small></h2>{!canvasOnly && <Link className="ws-link-button" to="/canvases">查看全部 <ArrowUpRight size={13} /></Link>}</div><div className="ws-toolbar"><div className="ws-toolbar-left"><div className="ws-search"><Search size={15} /><input aria-label="搜索画布" placeholder="搜索画布标题…" value={search} onChange={event => setSearch(event.target.value)} /></div></div><div className="ws-toolbar-right"><button className="ws-button ws-button-small" onClick={() => setSortDesc(value => !value)}><ArrowDownWideNarrow size={13} />{sortDesc ? '最近更新' : '最早更新'}</button><button className="ws-button ws-button-small" onClick={() => setParams(trashOpen ? {} : { trash: '1' })}><Trash2 size={13} />回收站{trash.length ? ` · ${trash.length}` : ''}</button></div></div>
    {trashOpen && <div className="ws-panel" style={{ marginBottom: 22 }}><div className="ws-panel-head"><h3>回收站</h3><button className="ws-link-button" onClick={() => setParams({})}>收起</button></div>{!trash.length ? <div className="ws-empty" style={{ minHeight: 130, padding: 25 }}><p>回收站为空，所有灵感都好好保存在这里。</p></div> : trash.map(document => <div className="ws-list-row" key={document.id}><FileText size={20} style={{ color: 'var(--ws-muted)' }} /><div><h3>{document.title}</h3><p>删除于 {timeLabel(document.deletedAt)}</p></div><div className="ws-list-row-end"><button className="ws-button ws-button-small" disabled={busy} onClick={() => void restore(document.id)}><Undo2 size={12} />恢复</button><button className="ws-button ws-button-small ws-button-danger" disabled={busy} onClick={() => void removeForever(document.id)}>彻底删除</button></div></div>)}</div>}
    {loading ? <div className="ws-skeleton-grid">{Array.from({ length: 4 }, (_, index) => <div className="ws-skeleton" key={index} />)}</div> : !shown.length ? <div className="ws-panel"><EmptyState title={search ? '暂时没有找到这张画布' : '你的第一张画布，从这里开始'} description={search ? '试试其他关键词，或清空搜索查看全部画布。' : '自由绘制、整理灵感，或为项目建立一份直观的设计说明。'}>{!search && <button className="ws-button ws-button-primary" disabled={busy} onClick={() => void createCanvas()}><Plus size={14} />新建画布</button>}</EmptyState></div> : <div className="ws-grid ws-grid-canvases">{(canvasOnly || search ? shown : shown.slice(0, 8)).map(document => <article className="ws-panel ws-canvas-card" key={document.id}><button className="ws-canvas-preview" style={{ width: '100%', border: 0 }} aria-label={`打开画布 ${document.title}`} onClick={() => navigate(`/editor/${document.id}`)}>{document.thumbnail ? <img src={document.thumbnail} alt={document.title} /> : <div className="ws-canvas-blank"><Layers size={27} strokeWidth={1.3} /></div>}{document.permission && document.permission !== 'owner' && <span className="ws-tag">{document.permission === 'edit' ? '可编辑' : '只读'}</span>}</button><div className="ws-canvas-info"><div style={{ minWidth: 0 }}><h3>{document.title}</h3><p>{timeLabel(document.updatedAt)}</p></div><div className="ws-canvas-card-actions"><button className="ws-icon-button" title="画布分享与编辑链接" aria-label={`分享 ${document.title}`} onClick={() => setShareId(document.id)}><Share2 size={13} /></button><button className="ws-icon-button" title="AI 只读入口" aria-label={`让 AI 读取 ${document.title}`} onClick={() => setAIDocument(document)}><Sparkles size={13} /></button><button className="ws-icon-button" title="移至回收站" aria-label={`删除 ${document.title}`} disabled={busy} onClick={() => void remove(document.id)}><Trash2 size={13} /></button></div></div></article>)}</div>}
    {shareId && <ShareDialog projectId={shareId} onClose={() => setShareId(null)} />}{aiDocument && <AIShareDialog kind="canvas" resourceId={aiDocument.id} title={aiDocument.title} onClose={() => setAIDocument(null)} />}
  </>
}
