'use strict'
// Regression checks for premature activation, hostname drift, and extra exposure.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { check } = require('./dior-tunnel-check.cjs')
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dior-tunnel-check-'))
const write = (name, data) => fs.writeFileSync(path.join(root, name), data, 'utf8')
try {
  const cf = fs.readFileSync(path.join(__dirname, 'cloudflare.yml.example'), 'utf8')
  const frp = fs.readFileSync(path.join(__dirname, 'frpc.toml.example'), 'utf8')
  write('provider', 'disabled\n')
  write('public-url', 'https://board.owner-domain.net\n')
  assert.throws(() => check({ root, staticOnly: true }), /unconfigured/)
  write('provider', 'quick\n')
  fs.unlinkSync(path.join(root, 'public-url'))
  assert.equal(check({ root, staticOnly: true }).publicUrlFile, '/var/lib/dior-tunnel/public-url')
  assert.equal(check({ root, staticOnly: true }).hostnamePermanent, false)
  write('public-url', 'https://board.owner-domain.net\n')
  write('provider', 'cloudflare\n')
  write('cloudflare.yml', cf)
  assert.throws(() => check({ root, staticOnly: true }), /named fixed/)
  const configured = cf.replace('REPLACE_WITH_TUNNEL_UUID', '01234567-89ab-4def-8123-456789abcdef')
    .replace('REPLACE_WITH_FIXED_HOSTNAME', 'board.owner-domain.net')
  write('cloudflare.yml', configured)
  assert.equal(check({ root, staticOnly: true }).publicConnectivityVerified, false)
  write('cloudflare.yml', configured.replace('board.owner-domain.net', 'random.trycloudflare.com'))
  assert.throws(() => check({ root, staticOnly: true }), /named fixed/)
  write('cloudflare.yml', configured.replace('  - service: http_status:404', '  - hostname: extra.owner-domain.net\n    service: http://127.0.0.1:3000\n  - service: http_status:404'))
  assert.throws(() => check({ root, staticOnly: true }), /Exactly one public hostname/)
  write('cloudflare.yml', configured)
  write('public-url', 'https://changed.owner-domain.net\n')
  assert.throws(() => check({ root, staticOnly: true }), /must match/)
  write('public-url', 'https://board.owner-domain.net/path\n')
  assert.throws(() => check({ root, staticOnly: true }), /no port, path/)
  write('public-url', 'https://127.0.0.1\n')
  assert.throws(() => check({ root, staticOnly: true }), /fixed DNS hostname/)
  write('public-url', 'https://board.owner-domain.net\n')
  write('cloudflare.yml', configured.replace('http://127.0.0.1:3000', 'http://172.16.42.1:22'))
  assert.throws(() => check({ root, staticOnly: true }), /Only local FlowBoard/)
  write('cloudflare.yml', configured.replace('http_status:404', 'http://127.0.0.1:3000'))
  assert.throws(() => check({ root, staticOnly: true }), /final 404/)
  write('provider', 'frp\n')
  write('frpc.toml', frp)
  assert.throws(() => check({ root, staticOnly: true }), /VPS hostname/)
  const frpc = frp.replaceAll('REPLACE_WITH_VPS_HOSTNAME', 'tunnel.owner-domain.net')
  write('frpc.toml', frpc)
  assert.equal(check({ root, staticOnly: true }).provider, 'frp')
  write('frpc.toml', frpc.replace('loginFailExit = false', 'loginFailExit = true'))
  assert.throws(() => check({ root, staticOnly: true }), /reconnecting TLS/)
  write('frpc.toml', frpc.replace('transport.tls.enable = true', 'transport.tls.enable = false'))
  assert.throws(() => check({ root, staticOnly: true }), /reconnecting TLS/)
  write('frpc.toml', frpc + '\n[[proxies]]\nname="extra"\ntype="tcp"\nlocalPort=22\nremotePort=63001\n')
  assert.throws(() => check({ root, staticOnly: true }), /one FlowBoard/)
  console.log('PASS: unconfigured refusal; account-free quick mode; fixed-domain agreement; HTTPS origin shape; single local ingress; 404 fallback; reconnect and TLS requirements; one FRP proxy')
} finally {
  fs.rmSync(root, { recursive: true, force: true })
}
